package main

import (
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"

	"golang.org/x/tools/go/packages"
)

const (
	generatedPrefix = "// Code generated by maxminddb-gen"
	mmdbdataPath    = "github.com/oschwald/maxminddb-golang/v2/mmdbdata"
)

type generator struct {
	structs        map[*types.Named]structInfo
	visiting       map[*types.Named]bool
	importPackages map[string]*types.Package
	importNames    map[string]string
	pkg            *packages.Package
	unmarshaler    *types.Interface
	cursorDecoder  *types.Interface
	targets        []*types.Named
	nextID         int
	usesFmt        bool
	usesMath       bool
}

type structInfo struct {
	named  *types.Named
	fields []fieldInfo
}

type fieldInfo struct {
	plan *decodePlan
	name string
	goID string
}

type decodeKind uint8

const (
	decodeBasic decodeKind = iota
	decodeBytes
	decodePointer
	decodeSlice
	decodeMap
	decodeStruct
	decodeUnmarshaler
	decodeCursorUnmarshaler
)

type decodePlan struct {
	typ   types.Type
	key   types.Type
	basic *types.Basic
	elem  *decodePlan
	named *types.Named
	kind  decodeKind
}

func generatePackage(
	targetNames []string,
	output, buildConstraint string,
	diagnostics io.Writer,
) error {
	if diagnostics == nil {
		diagnostics = io.Discard
	}
	absOutput, err := filepath.Abs(output)
	if err != nil {
		return err
	}
	overlay, err := outputOverlay(absOutput, targetNames)
	if err != nil {
		return err
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo |
			packages.NeedTypesSizes,
		Overlay: overlay,
		Tests:   false,
	}
	pkgs, err := packages.Load(cfg, ".", mmdbdataPath)
	if err != nil {
		return err
	}
	if packages.PrintErrors(pkgs) != 0 {
		return errors.New("loading target package")
	}
	var targetPackage, mmdbdataPackage *packages.Package
	for _, loaded := range pkgs {
		if loaded.PkgPath == mmdbdataPath {
			mmdbdataPackage = loaded
		} else {
			targetPackage = loaded
		}
	}
	if targetPackage == nil || mmdbdataPackage == nil {
		return fmt.Errorf("loading target and %s packages", mmdbdataPath)
	}
	unmarshaler, err := packageInterface(mmdbdataPackage.Types, "Unmarshaler")
	if err != nil {
		return err
	}
	cursorDecoder, err := packageInterface(mmdbdataPackage.Types, "CursorUnmarshaler")
	if err != nil {
		return err
	}

	g := &generator{
		pkg:            targetPackage,
		structs:        make(map[*types.Named]structInfo),
		visiting:       make(map[*types.Named]bool),
		importPackages: make(map[string]*types.Package),
		importNames:    make(map[string]string),
		unmarshaler:    unmarshaler,
		cursorDecoder:  cursorDecoder,
	}
	seenTargets := make(map[string]bool)
	for _, name := range targetNames {
		if seenTargets[name] {
			return fmt.Errorf("duplicate target type %q", name)
		}
		seenTargets[name] = true
		obj := g.pkg.Types.Scope().Lookup(name)
		if obj == nil {
			return fmt.Errorf("type %q is not declared in package %s", name, g.pkg.PkgPath)
		}
		typeName, ok := obj.(*types.TypeName)
		if !ok {
			return g.positionError(obj.Pos(), "%q is not a type", name)
		}
		named, ok := typeName.Type().(*types.Named)
		if !ok {
			return g.positionError(obj.Pos(), "%q is not a named type", name)
		}
		if _, ok := named.Underlying().(*types.Struct); !ok {
			return g.positionError(obj.Pos(), "target %s is not a struct", name)
		}
		if method := lookupUnmarshalMethod(named); method != nil {
			if g.implements(named, g.unmarshaler) {
				if _, err := fmt.Fprintf(
					diagnostics,
					"maxminddb-gen: skipping %s: handwritten UnmarshalMaxMindDB method\n",
					name,
				); err != nil {
					return err
				}
				continue
			}
			return g.positionError(
				method.Pos(),
				"type %s has an incompatible UnmarshalMaxMindDB method; want func(*mmdbdata.Decoder) error",
				name,
			)
		}
		if method := lookupCursorUnmarshalMethod(named); method != nil {
			if g.implements(named, g.cursorDecoder) {
				if _, err := fmt.Fprintf(
					diagnostics,
					"maxminddb-gen: skipping %s: handwritten UnmarshalMaxMindDBCursor method\n",
					name,
				); err != nil {
					return err
				}
				continue
			}
			return g.positionError(
				method.Pos(),
				"type %s has an incompatible UnmarshalMaxMindDBCursor method; want func(mmdbdata.Cursor) (mmdbdata.Cursor, error)",
				name,
			)
		}
		if named.TypeParams().Len() != 0 {
			return g.positionError(obj.Pos(), "generic target %s is not supported", name)
		}
		if g.pkg.Types.Scope().Lookup(helperName(named)) != nil {
			return g.positionError(
				obj.Pos(),
				"generated helper %s collides with an existing declaration",
				helperName(named),
			)
		}
		g.targets = append(g.targets, named)
	}
	if len(g.targets) == 0 {
		return errors.New("no decoders remain after excluding types with handwritten methods")
	}

	for _, target := range g.targets {
		if err := g.analyzeStruct(target); err != nil {
			return err
		}
	}
	g.prepareImports()
	source, err := g.render(buildConstraint)
	if err != nil {
		return err
	}
	return writeAtomic(absOutput, source)
}

func outputOverlay(path string, targetNames []string) (map[string][]byte, error) {
	overlay := make(map[string][]byte)
	contents, err := os.ReadFile(path)
	if err == nil {
		file, generated, parseErr := parseGeneratedFile(path, contents)
		if parseErr != nil {
			return nil, parseErr
		}
		if !generated {
			return nil, fmt.Errorf("output %s exists and was not created by maxminddb-gen", path)
		}
		overlay[path] = packageStub(file)
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}

	cwd, err := os.Getwd()
	if err != nil {
		return nil, err
	}
	entries, err := os.ReadDir(cwd)
	if err != nil {
		return nil, err
	}
	targets := make(map[string]bool, len(targetNames))
	for _, name := range targetNames {
		targets[name] = true
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" ||
			strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		candidate := filepath.Join(cwd, entry.Name())
		if candidate == path {
			continue
		}
		contents, err := os.ReadFile(candidate)
		if err != nil {
			return nil, err
		}
		if !strings.Contains(string(contents), generatedPrefix) {
			continue
		}
		file, generated, err := parseGeneratedFile(candidate, contents)
		if err != nil {
			return nil, err
		}
		if generated && generatedFileOverlaps(file, targets) {
			overlay[candidate] = packageStub(file)
		}
	}
	return overlay, nil
}

func parseGeneratedFile(path string, contents []byte) (*ast.File, bool, error) {
	file, err := parser.ParseFile(
		token.NewFileSet(),
		path,
		contents,
		parser.ParseComments,
	)
	if err != nil {
		return nil, false, fmt.Errorf("reading package from prior output: %w", err)
	}
	for _, group := range file.Comments {
		if group.Pos() > file.Package {
			break
		}
		for _, comment := range group.List {
			if isGeneratedMarker(comment.Text) {
				return file, true, nil
			}
		}
	}
	return file, false, nil
}

func isGeneratedMarker(comment string) bool {
	const suffix = "; DO NOT EDIT."
	if comment == generatedPrefix+suffix {
		return true
	}
	prefix := generatedPrefix + " "
	if !strings.HasPrefix(comment, prefix) || !strings.HasSuffix(comment, suffix) {
		return false
	}
	version := comment[len(prefix) : len(comment)-len(suffix)]
	return version != "" && !strings.ContainsAny(version, " \t\r\n")
}

func generatedFileOverlaps(file *ast.File, targets map[string]bool) bool {
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Recv == nil ||
			(function.Name.Name != "UnmarshalMaxMindDB" &&
				function.Name.Name != "UnmarshalMaxMindDBCursor") {
			continue
		}
		receiver := function.Recv.List[0].Type
		if pointer, ok := receiver.(*ast.StarExpr); ok {
			receiver = pointer.X
		}
		if identifier, ok := receiver.(*ast.Ident); ok && targets[identifier.Name] {
			return true
		}
	}
	return false
}

func packageStub(file *ast.File) []byte {
	return []byte("package " + file.Name.Name + "\n")
}

func writeAtomic(path string, contents []byte) error {
	dir := filepath.Dir(path)
	temp, err := os.CreateTemp(dir, ".maxminddb-gen-*")
	if err != nil {
		return err
	}
	tempName := temp.Name()
	defer func() { _ = os.Remove(tempName) }()
	if _, err := temp.Write(contents); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Chmod(0o644); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Sync(); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	return replaceFile(tempName, path)
}

func (g *generator) analyzeStruct(named *types.Named) error {
	if named.TypeParams().Len() != 0 {
		return g.positionError(
			named.Obj().Pos(),
			"generic struct %s is not supported",
			named.Obj().Name(),
		)
	}
	if _, ok := g.structs[named]; ok {
		return nil
	}
	if g.visiting[named] {
		return g.positionError(
			named.Obj().Pos(),
			"recursive type graph through %s is not supported",
			named.Obj().Name(),
		)
	}
	g.visiting[named] = true
	defer delete(g.visiting, named)

	structure := named.Underlying().(*types.Struct)
	info := structInfo{named: named}
	seenNames := make(map[string]token.Pos)
	for i := range structure.NumFields() {
		field := structure.Field(i)
		if !field.Exported() {
			continue
		}
		if field.Embedded() {
			return g.positionError(
				field.Pos(),
				"embedded field %s is not yet supported",
				field.Name(),
			)
		}
		tag, tagged, err := maxminddbTag(structure.Tag(i))
		if err != nil {
			return g.positionError(field.Pos(), "field %s: %v", field.Name(), err)
		}
		if tag == "-" {
			continue
		}
		name := field.Name()
		if tagged {
			name = tag
		}
		if previous, exists := seenNames[name]; exists {
			return g.positionError(
				field.Pos(),
				"field %s conflicts with another field at %s for MMDB key %q",
				field.Name(),
				g.pkg.Fset.Position(previous),
				name,
			)
		}
		seenNames[name] = field.Pos()
		plan, err := g.analyzeType(field.Type())
		if err != nil {
			return g.positionError(field.Pos(), "field %s: %v", field.Name(), err)
		}
		info.fields = append(
			info.fields,
			fieldInfo{plan: plan, name: name, goID: field.Name()},
		)
	}
	g.structs[named] = info
	return nil
}

func (g *generator) analyzeType(t types.Type) (*decodePlan, error) {
	if g.implements(t, g.cursorDecoder) {
		return &decodePlan{typ: t, kind: decodeCursorUnmarshaler}, nil
	}
	if g.implements(t, g.unmarshaler) {
		return &decodePlan{typ: t, kind: decodeUnmarshaler}, nil
	}
	switch value := t.(type) {
	case *types.Pointer:
		elem, err := g.analyzeType(value.Elem())
		return &decodePlan{typ: t, kind: decodePointer, elem: elem}, err
	case *types.Named:
		if _, ok := value.Underlying().(*types.Struct); ok &&
			value.Origin().TypeParams().Len() != 0 {
			return nil, fmt.Errorf("generic struct %s is not supported", value.Obj().Name())
		}
		if basic, ok := value.Underlying().(*types.Basic); ok {
			if err := supportedBasic(basic); err != nil {
				return nil, err
			}
			return &decodePlan{typ: t, kind: decodeBasic, basic: basic}, nil
		}
		if _, ok := value.Underlying().(*types.Struct); ok {
			if value.Obj().Pkg() != g.pkg.Types {
				return nil, fmt.Errorf(
					"struct type %s is owned by another package and does not implement mmdbdata.CursorUnmarshaler or mmdbdata.Unmarshaler",
					value,
				)
			}
			if err := g.analyzeStruct(value); err != nil {
				return nil, err
			}
			return &decodePlan{typ: t, kind: decodeStruct, named: value}, nil
		}
		if g.visiting[value] {
			return nil, fmt.Errorf(
				"recursive type graph through %s is not supported",
				value.Obj().Name(),
			)
		}
		g.visiting[value] = true
		defer delete(g.visiting, value)
		plan, err := g.analyzeType(value.Underlying())
		if plan != nil && plan.kind == decodeBytes {
			slice := value.Underlying().(*types.Slice)
			elem, elemErr := g.analyzeType(slice.Elem())
			if elemErr != nil {
				return nil, elemErr
			}
			plan = &decodePlan{typ: t, kind: decodeSlice, elem: elem}
		} else if plan != nil {
			plan.typ = t
		}
		return plan, err
	case *types.Basic:
		if err := supportedBasic(value); err != nil {
			return nil, err
		}
		return &decodePlan{typ: t, kind: decodeBasic, basic: value}, nil
	case *types.Slice:
		if types.Identical(t, types.NewSlice(types.Typ[types.Byte])) {
			return &decodePlan{typ: t, kind: decodeBytes}, nil
		}
		elem, err := g.analyzeType(value.Elem())
		return &decodePlan{typ: t, kind: decodeSlice, elem: elem}, err
	case *types.Map:
		key, ok := value.Key().Underlying().(*types.Basic)
		if !ok || key.Kind() != types.String {
			return nil, fmt.Errorf("map key type must be string, found %s", value.Key())
		}
		elem, err := g.analyzeType(value.Elem())
		return &decodePlan{typ: t, kind: decodeMap, key: value.Key(), elem: elem}, err
	default:
		return nil, fmt.Errorf("unsupported type %s", t)
	}
}

func supportedBasic(basic *types.Basic) error {
	switch basic.Kind() {
	case types.Bool, types.String,
		types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
		types.Float32, types.Float64:
		return nil
	default:
		return fmt.Errorf("unsupported type %s", basic)
	}
}

func maxminddbTag(raw string) (string, bool, error) {
	for raw != "" {
		i := 0
		for i < len(raw) && raw[i] == ' ' {
			i++
		}
		raw = raw[i:]
		if raw == "" {
			break
		}

		i = 0
		for i < len(raw) && raw[i] > ' ' && raw[i] != ':' && raw[i] != '"' && raw[i] != 0x7f {
			i++
		}
		if i == 0 || i+1 >= len(raw) || raw[i] != ':' || raw[i+1] != '"' {
			if strings.HasPrefix(raw, "maxminddb") {
				return "", false, errors.New("malformed maxminddb struct tag")
			}
			next := strings.IndexByte(raw, ' ')
			if next < 0 {
				break
			}
			raw = raw[next+1:]
			continue
		}
		name := raw[:i]
		raw = raw[i+1:]

		i = 1
		for i < len(raw) && raw[i] != '"' {
			if raw[i] == '\\' {
				i++
			}
			i++
		}
		if i >= len(raw) {
			if name == "maxminddb" {
				return "", false, errors.New("unterminated maxminddb struct tag")
			}
			break
		}
		quotedValue := raw[:i+1]
		raw = raw[i+1:]
		if name != "maxminddb" {
			continue
		}
		if !utf8.ValidString(quotedValue) {
			return "", false, errors.New("invalid UTF-8 maxminddb struct tag")
		}
		value, err := strconv.Unquote(quotedValue)
		if err != nil {
			return "", false, fmt.Errorf("invalid maxminddb struct tag: %w", err)
		}
		if !utf8.ValidString(value) {
			return "", false, errors.New("invalid UTF-8 maxminddb struct tag")
		}
		if value == "" {
			return "", false, nil
		}
		return value, true, nil
	}
	return "", false, nil
}

func lookupUnmarshalMethod(named *types.Named) *types.Func {
	return lookupMethod(named, "UnmarshalMaxMindDB")
}

func lookupCursorUnmarshalMethod(named *types.Named) *types.Func {
	return lookupMethod(named, "UnmarshalMaxMindDBCursor")
}

func lookupMethod(named *types.Named, name string) *types.Func {
	selection := types.NewMethodSet(types.NewPointer(named)).Lookup(nil, name)
	if selection == nil {
		return nil
	}
	method, _ := selection.Obj().(*types.Func)
	return method
}

func packageInterface(pkg *types.Package, name string) (*types.Interface, error) {
	object := pkg.Scope().Lookup(name)
	if object == nil {
		return nil, fmt.Errorf("%s does not declare %s", pkg.Path(), name)
	}
	iface, ok := object.Type().Underlying().(*types.Interface)
	if !ok {
		return nil, fmt.Errorf("%s.%s is not an interface", pkg.Path(), name)
	}
	return iface.Complete(), nil
}

func (*generator) implements(t types.Type, iface *types.Interface) bool {
	if types.Implements(t, iface) {
		return true
	}
	if _, ok := t.(*types.Pointer); ok {
		return false
	}
	return types.Implements(types.NewPointer(t), iface)
}

func helperName(named *types.Named) string {
	return "maxminddbGenDecode" + named.Obj().Name()
}

func (g *generator) render(buildConstraint string) ([]byte, error) {
	var body strings.Builder
	infos := make([]structInfo, 0, len(g.structs))
	for _, info := range g.structs {
		infos = append(infos, info)
	}
	slices.SortFunc(infos, func(a, b structInfo) int {
		return strings.Compare(a.named.Obj().Name(), b.named.Obj().Name())
	})
	for _, info := range infos {
		g.emitStruct(&body, info)
	}
	for _, target := range g.targets {
		fmt.Fprintf(
			&body,
			"func (out *%s) UnmarshalMaxMindDBCursor(cursor mmdbdata.Cursor) (mmdbdata.Cursor, error) {\n",
			target.Obj().Name(),
		)
		fmt.Fprintf(&body, "\treturn %s(cursor, out)\n", helperName(target))
		body.WriteString("}\n\n")

		fmt.Fprintf(
			&body,
			"func (out *%s) UnmarshalMaxMindDB(decoder *mmdbdata.Decoder) error {\n",
			target.Obj().Name(),
		)
		fmt.Fprintf(&body, "\tnext, err := %s(decoder.Cursor(), out)\n", helperName(target))
		body.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
		body.WriteString("\treturn decoder.Advance(next)\n}\n\n")
	}

	var source strings.Builder
	if buildConstraint != "" {
		fmt.Fprintf(&source, "//go:build %s\n\n", buildConstraint)
	}
	fmt.Fprintf(&source, "%s; DO NOT EDIT.\n", generatedPrefix)
	fmt.Fprintf(
		&source,
		"// Requires github.com/oschwald/maxminddb-golang/v2 %s or newer.\n\n",
		minimumLibrary,
	)
	fmt.Fprintf(&source, "package %s\n\n", g.pkg.Name)
	g.emitImports(&source)
	source.WriteString(body.String())
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w\n%s", err, source.String())
	}
	return formatted, nil
}

func (g *generator) emitStruct(out *strings.Builder, info structInfo) {
	if len(info.fields) > 0 {
		g.usesFmt = true
	}
	fmt.Fprintf(
		out,
		"func %s(cursor mmdbdata.Cursor, out *%s) (mmdbdata.Cursor, error) {\n",
		helperName(info.named),
		info.named.Obj().Name(),
	)
	out.WriteString("\tentries, err := cursor.MapReader()\n")
	fmt.Fprintf(
		out,
		"\tif err != nil {\n\t\treturn mmdbdata.Cursor{}, mmdbdata.NormalizeUnmarshalError[%s](err)\n\t}\n",
		info.named.Obj().Name(),
	)
	out.WriteString("\tnext := entries.First()\n")
	out.WriteString("\tfor range entries.Len() {\n")
	out.WriteString("\t\tkey, valueCursor, keyErr := next.ReadMapKey()\n")
	out.WriteString("\t\tif keyErr != nil {\n\t\t\treturn mmdbdata.Cursor{}, keyErr\n\t\t}\n")
	out.WriteString("\t\tswitch string(key) {\n")
	for _, field := range info.fields {
		fmt.Fprintf(out, "\t\tcase %s:\n", strconv.Quote(field.name))
		g.emitDecode(out, field.plan, "valueCursor", "out."+field.goID, "next", "err", 3)
		fmt.Fprintf(
			out,
			"\t\t\tif err != nil {\n\t\t\t\treturn mmdbdata.Cursor{}, fmt.Errorf(\"decoding field %s: %%w\", %s)\n\t\t\t}\n",
			field.name,
			g.errorExpression(field.plan, "err"),
		)
	}
	out.WriteString("\t\tdefault:\n\t\t\tnext, err = valueCursor.Skip()\n\t\t}\n")
	out.WriteString("\t\tif err != nil {\n\t\t\treturn mmdbdata.Cursor{}, err\n\t\t}\n")
	out.WriteString("\t}\n")
	out.WriteString("\treturn entries.End(next)\n}\n\n")
}

func (g *generator) emitDecode(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
) {
	pad := strings.Repeat("\t", indent)
	switch plan.kind {
	case decodePointer:
		id := g.id()
		fmt.Fprintf(out, "%sif %s == nil {\n", pad, target)
		fmt.Fprintf(out, "%s\tvar decoded%d %s\n", pad, id, g.typeString(plan.elem.typ))
		g.emitDecode(
			out,
			plan.elem,
			cursor,
			fmt.Sprintf("decoded%d", id),
			next,
			errName,
			indent+1,
		)
		fmt.Fprintf(
			out,
			"%s\tif %s == nil {\n%s\t\t%s = &decoded%d\n%s\t}\n",
			pad,
			errName,
			pad,
			target,
			id,
			pad,
		)
		fmt.Fprintf(out, "%s} else {\n", pad)
		g.emitDecode(out, plan.elem, cursor, "*"+target, next, errName, indent+1)
		fmt.Fprintf(out, "%s}\n", pad)
	case decodeCursorUnmarshaler:
		fmt.Fprintf(
			out,
			"%s%s, %s = %s.UnmarshalCursor(&%s)\n",
			pad,
			next,
			errName,
			cursor,
			target,
		)
	case decodeUnmarshaler:
		fmt.Fprintf(out, "%s%s, %s = %s.Unmarshal(&%s)\n", pad, next, errName, cursor, target)
	case decodeStruct:
		fmt.Fprintf(
			out,
			"%s%s, %s = %s(%s, &%s)\n",
			pad,
			next,
			errName,
			helperName(plan.named),
			cursor,
			target,
		)
	case decodeBasic:
		g.emitBasic(out, plan.typ, plan.basic, cursor, target, next, errName, indent)
	case decodeBytes:
		id := g.id()
		fmt.Fprintf(out, "%svar bytes%d []byte\n", pad, id)
		fmt.Fprintf(out, "%sbytes%d, %s, %s = %s.ReadBytes()\n", pad, id, next, errName, cursor)
		fmt.Fprintf(
			out,
			"%sif %s == nil {\n%s\t%s = append(%s[:0], bytes%d...)\n%s}\n",
			pad,
			errName,
			pad,
			target,
			target,
			id,
			pad,
		)
	case decodeSlice:
		g.emitSlice(out, plan, cursor, target, next, errName, indent)
	case decodeMap:
		g.emitMap(out, plan, cursor, target, next, errName, indent)
	default:
		panic("unsupported decode plan for " + plan.typ.String())
	}
}

func (g *generator) emitBasic(
	out *strings.Builder,
	original types.Type,
	basic *types.Basic,
	cursor, target, next, errName string,
	indent int,
) {
	pad := strings.Repeat("\t", indent)
	typeName := g.typeString(original)
	id := g.id()
	switch basic.Kind() {
	case types.String:
		fmt.Fprintf(
			out,
			"%svar value%d string\n%svalue%d, %s, %s = %s.ReadString()\n",
			pad,
			id,
			pad,
			id,
			next,
			errName,
			cursor,
		)
		fmt.Fprintf(
			out,
			"%sif %s == nil {\n%s\t%s = %s(value%d)\n%s}\n",
			pad,
			errName,
			pad,
			target,
			typeName,
			id,
			pad,
		)
	case types.Bool:
		fmt.Fprintf(
			out,
			"%svar value%d bool\n%svalue%d, %s, %s = %s.ReadBool()\n",
			pad,
			id,
			pad,
			id,
			next,
			errName,
			cursor,
		)
		fmt.Fprintf(
			out,
			"%sif %s == nil {\n%s\t%s = %s(value%d)\n%s}\n",
			pad,
			errName,
			pad,
			target,
			typeName,
			id,
			pad,
		)
	case types.Float32, types.Float64:
		if basic.Kind() == types.Float32 {
			g.usesMath = true
		}
		fmt.Fprintf(
			out,
			"%svar value%d float64\n%svalue%d, %s, %s = %s.ReadFloat()\n",
			pad,
			id,
			pad,
			id,
			next,
			errName,
			cursor,
		)
		fmt.Fprintf(
			out,
			"%sif %s == nil {\n%s\tconverted%d := %s(value%d)\n",
			pad,
			errName,
			pad,
			id,
			typeName,
			id,
		)
		if basic.Kind() == types.Float32 {
			fmt.Fprintf(
				out,
				"%s\tif math.IsInf(float64(converted%d), 0) && !math.IsInf(value%d, 0) {\n",
				pad,
				id,
				id,
			)
			fmt.Fprintf(
				out,
				"%s\t\t%s = mmdbdata.NewUnmarshalTypeError[%s](value%d)\n%s\t} else {\n%s\t\t%s = converted%d\n%s\t}\n",
				pad,
				errName,
				typeName,
				id,
				pad,
				pad,
				target,
				id,
				pad,
			)
		} else {
			fmt.Fprintf(out, "%s\t%s = converted%d\n", pad, target, id)
		}
		fmt.Fprintf(out, "%s}\n", pad)
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64:
		g.emitInteger(out, original, basic, cursor, target, next, errName, indent, id)
	default:
		panic("unsupported basic type")
	}
}

//nolint:revive // Emission context is clearer as explicit arguments.
func (g *generator) emitInteger(
	out *strings.Builder,
	original types.Type,
	basic *types.Basic,
	cursor, target, next, errName string,
	indent, id int,
) {
	pad := strings.Repeat("\t", indent)
	typeName := g.typeString(original)
	signed := basic.Info()&types.IsInteger != 0 && basic.Info()&types.IsUnsigned == 0
	fmt.Fprintf(out, "%svar integerValue%d uint64\n", pad, id)
	fmt.Fprintf(out, "%svar integerSigned%d bool\n", pad, id)
	fmt.Fprintf(
		out,
		"%sintegerValue%d, integerSigned%d, %s, %s = %s.ReadInteger()\n",
		pad,
		id,
		id,
		next,
		errName,
		cursor,
	)
	fmt.Fprintf(
		out,
		"%sif %s == nil && integerSigned%d {\n%s\tsignedValue%d := int64(integerValue%d)\n%s\tconverted%d := %s(signedValue%d)\n",
		pad,
		errName,
		id,
		pad,
		id,
		id,
		pad,
		id,
		typeName,
		id,
	)
	if signed {
		fmt.Fprintf(out, "%s\tif int64(converted%d) != signedValue%d {\n", pad, id, id)
	} else {
		fmt.Fprintf(
			out,
			"%s\tif signedValue%d < 0 || uint64(converted%d) != uint64(signedValue%d) {\n",
			pad,
			id,
			id,
			id,
		)
	}
	fmt.Fprintf(
		out,
		"%s\t\t%s = mmdbdata.NewUnmarshalTypeError[%s](signedValue%d)\n%s\t} else {\n%s\t\t%s = converted%d\n%s\t}\n%s} else if %s == nil {\n",
		pad,
		errName,
		typeName,
		id,
		pad,
		pad,
		target,
		id,
		pad,
		pad,
		errName,
	)
	fmt.Fprintf(out, "%s\tunsignedValue%d := integerValue%d\n", pad, id, id)
	fmt.Fprintf(out, "%s\tconverted%d := %s(unsignedValue%d)\n", pad, id, typeName, id)
	if signed {
		fmt.Fprintf(
			out,
			"%s\tif converted%d < 0 || uint64(converted%d) != unsignedValue%d {\n",
			pad,
			id,
			id,
			id,
		)
	} else {
		fmt.Fprintf(out, "%s\tif uint64(converted%d) != unsignedValue%d {\n", pad, id, id)
	}
	fmt.Fprintf(
		out,
		"%s\t\t%s = mmdbdata.NewUnmarshalTypeError[%s](unsignedValue%d)\n%s\t} else {\n%s\t\t%s = converted%d\n%s\t}\n%s}\n",
		pad,
		errName,
		typeName,
		id,
		pad,
		pad,
		target,
		id,
		pad,
		pad,
	)
}

func (g *generator) emitSlice(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
) {
	pad := strings.Repeat("\t", indent)
	id := g.id()
	fmt.Fprintf(out, "%svalues%d, openErr%d := %s.Slice()\n", pad, id, id, cursor)
	fmt.Fprintf(
		out,
		"%sif openErr%d != nil {\n%s\t%s = mmdbdata.NormalizeUnmarshalError[%s](openErr%d)\n%s} else {\n",
		pad,
		id,
		pad,
		errName,
		g.typeString(plan.typ),
		id,
		pad,
	)
	fmt.Fprintf(
		out,
		"%s\tsizeValue%d, sizeReady%d := values%d.SizeForCapacity(cap(%s))\n%s\tif !sizeReady%d {\n%s\t\tsizeValue%d, %s = values%d.Size()\n%s\t}\n%s\tif %s == nil {\n%s\t\tsize%d := int(sizeValue%d)\n%s\t\toldLen%d := len(%s)\n",
		pad,
		id,
		id,
		id,
		target,
		pad,
		id,
		pad,
		id,
		errName,
		id,
		pad,
		pad,
		errName,
		pad,
		id,
		id,
		pad,
		id,
		target,
	)
	fmt.Fprintf(
		out,
		"%s\tif %s == nil || cap(%s) < size%d {\n%s\t\t%s = make(%s, size%d)\n%s\t} else {\n",
		pad,
		target,
		target,
		id,
		pad,
		target,
		g.typeString(plan.typ),
		id,
		pad,
	)
	fmt.Fprintf(
		out,
		"%s\t\t%s = %s[:size%d]\n%s\t\tclear(%s)\n",
		pad,
		target,
		target,
		id,
		pad,
		target,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif oldLen%d > size%d {\n%s\t\t\tclear(%s[size%d:oldLen%d])\n%s\t\t}\n%s\t}\n",
		pad,
		id,
		id,
		pad,
		target,
		id,
		id,
		pad,
		pad,
	)
	fmt.Fprintf(out, "%s\tvar elementNext%d mmdbdata.Cursor\n", pad, id)
	fmt.Fprintf(
		out,
		"%s\tfor {\n%s\t\tindexValue%d, elementCursor%d, ok%d := values%d.Next(elementNext%d)\n%s\t\tif !ok%d {\n%s\t\t\tbreak\n%s\t\t}\n%s\t\tindex%d := int(indexValue%d)\n%s\t\tvar elementErr%d error\n",
		pad,
		pad,
		id,
		id,
		id,
		id,
		id,
		pad,
		id,
		pad,
		pad,
		pad,
		id,
		id,
		pad,
		id,
	)
	g.emitDecode(
		out,
		plan.elem,
		fmt.Sprintf("elementCursor%d", id),
		fmt.Sprintf("%s[index%d]", target, id),
		fmt.Sprintf("elementNext%d", id),
		fmt.Sprintf("elementErr%d", id),
		indent+2,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif elementErr%d != nil {\n%s\t\t\t%s = fmt.Errorf(\"decoding index %%d: %%w\", index%d, %s)\n%s\t\t\tbreak\n%s\t\t}\n",
		pad,
		id,
		pad,
		errName,
		id,
		g.errorExpression(plan.elem, fmt.Sprintf("elementErr%d", id)),
		pad,
		pad,
	)
	fmt.Fprintf(out, "%s\t}\n", pad)
	fmt.Fprintf(
		out,
		"%s\tif %s == nil {\n%s\t\t%s, %s = values%d.End()\n%s\t}\n%s\t}\n%s}\n",
		pad,
		errName,
		pad,
		next,
		errName,
		id,
		pad,
		pad,
		pad,
	)
}

func (g *generator) emitMap(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
) {
	pad := strings.Repeat("\t", indent)
	id := g.id()
	fmt.Fprintf(out, "%sentries%d, openErr%d := %s.Map()\n", pad, id, id, cursor)
	fmt.Fprintf(
		out,
		"%sif openErr%d != nil {\n%s\t%s = mmdbdata.NormalizeUnmarshalError[%s](openErr%d)\n%s} else {\n",
		pad,
		id,
		pad,
		errName,
		g.typeString(plan.typ),
		id,
		pad,
	)
	fmt.Fprintf(
		out,
		"%s\tsize%d := entries%d.Size()\n%s\tif %s == nil {\n%s\t\t%s = make(%s, int(size%d))\n%s\t}\n",
		pad,
		id,
		id,
		pad,
		target,
		pad,
		target,
		g.typeString(plan.typ),
		id,
		pad,
	)
	fmt.Fprintf(out, "%s\tvar valueNext%d mmdbdata.Cursor\n", pad, id)
	fmt.Fprintf(
		out,
		"%s\tfor {\n%s\t\trawKey%d, valueCursor%d, ok%d := entries%d.Next(valueNext%d)\n%s\t\tif !ok%d {\n%s\t\t\tbreak\n%s\t\t}\n%s\t\tkey%d := %s(string(rawKey%d))\n%s\t\tvar decoded%d %s\n%s\t\tvar valueErr%d error\n",
		pad,
		pad,
		id,
		id,
		id,
		id,
		id,
		pad,
		id,
		pad,
		pad,
		pad,
		id,
		g.typeString(plan.key),
		id,
		pad,
		id,
		g.typeString(plan.elem.typ),
		pad,
		id,
	)
	g.emitDecode(
		out,
		plan.elem,
		fmt.Sprintf("valueCursor%d", id),
		fmt.Sprintf("decoded%d", id),
		fmt.Sprintf("valueNext%d", id),
		fmt.Sprintf("valueErr%d", id),
		indent+2,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif valueErr%d != nil {\n%s\t\t\t%s = fmt.Errorf(\"decoding map key %%q: %%w\", key%d, %s)\n%s\t\t\tbreak\n%s\t\t}\n",
		pad,
		id,
		pad,
		errName,
		id,
		g.errorExpression(plan.elem, fmt.Sprintf("valueErr%d", id)),
		pad,
		pad,
	)
	fmt.Fprintf(out, "%s\t\t%s[key%d] = decoded%d\n", pad, target, id, id)
	fmt.Fprintf(out, "%s\t}\n", pad)
	fmt.Fprintf(
		out,
		"%s\tif %s == nil {\n%s\t\t%s, %s = entries%d.End()\n%s\t}\n%s}\n",
		pad,
		errName,
		pad,
		next,
		errName,
		id,
		pad,
		pad,
	)
}

func (g *generator) errorExpression(plan *decodePlan, name string) string {
	for plan.kind == decodePointer {
		plan = plan.elem
	}
	if plan.kind == decodeBasic || plan.kind == decodeBytes {
		return fmt.Sprintf(
			"mmdbdata.NormalizeUnmarshalError[%s](%s)",
			g.typeString(plan.typ),
			name,
		)
	}
	return name
}

func (g *generator) id() int {
	g.nextID++
	return g.nextID
}

func (g *generator) typeString(t types.Type) string {
	return types.TypeString(t, func(pkg *types.Package) string {
		if pkg == g.pkg.Types {
			return ""
		}
		name, ok := g.importNames[pkg.Path()]
		if !ok {
			panic("missing generated import for " + pkg.Path())
		}
		return name
	})
}

func (g *generator) prepareImports() {
	for _, info := range g.structs {
		for _, field := range info.fields {
			g.collectPlanImports(field.plan, false)
		}
	}

	paths := make([]string, 0, len(g.importPackages))
	for path := range g.importPackages {
		if path == mmdbdataPath {
			g.importNames[path] = "mmdbdata"
			continue
		}
		paths = append(paths, path)
	}
	slices.Sort(paths)
	used := map[string]bool{"fmt": true, "math": true, "mmdbdata": true}
	for _, path := range paths {
		pkg := g.importPackages[path]
		name := pkg.Name()
		for suffix := 2; used[name]; suffix++ {
			name = pkg.Name() + strconv.Itoa(suffix)
		}
		used[name] = true
		g.importNames[path] = name
	}
}

func (g *generator) collectPlanImports(plan *decodePlan, typeRequired bool) {
	if typeRequired || plan.kind == decodeBasic || plan.kind == decodeSlice ||
		plan.kind == decodeMap {
		g.collectTypeImports(plan.typ)
	}
	switch plan.kind {
	case decodePointer, decodeSlice:
		g.collectPlanImports(plan.elem, true)
	case decodeMap:
		g.collectTypeImports(plan.key)
		g.collectPlanImports(plan.elem, true)
	default:
	}
}

func (g *generator) collectTypeImports(t types.Type) {
	types.TypeString(t, func(pkg *types.Package) string {
		if pkg != g.pkg.Types {
			g.importPackages[pkg.Path()] = pkg
		}
		return pkg.Name()
	})
}

type generatedImport struct {
	path string
	name string
}

func (g *generator) emitImports(source *strings.Builder) {
	imports := make([]generatedImport, 0, len(g.importPackages)+3)
	if g.usesFmt {
		imports = append(imports, generatedImport{path: "fmt"})
	}
	if g.usesMath {
		imports = append(imports, generatedImport{path: "math"})
	}
	for path, pkg := range g.importPackages {
		if path == mmdbdataPath {
			continue
		}
		name := g.importNames[path]
		if name == pkg.Name() {
			name = ""
		}
		imports = append(imports, generatedImport{path: path, name: name})
	}
	imports = append(imports, generatedImport{
		path: mmdbdataPath,
	})
	slices.SortFunc(imports, func(a, b generatedImport) int {
		aThirdParty := strings.Contains(strings.SplitN(a.path, "/", 2)[0], ".")
		bThirdParty := strings.Contains(strings.SplitN(b.path, "/", 2)[0], ".")
		if aThirdParty != bThirdParty {
			if aThirdParty {
				return 1
			}
			return -1
		}
		return strings.Compare(a.path, b.path)
	})

	source.WriteString("import (\n")
	thirdParty := false
	for _, generatedImport := range imports {
		isThirdParty := strings.Contains(strings.SplitN(generatedImport.path, "/", 2)[0], ".")
		if isThirdParty && !thirdParty {
			if generatedImport.path != imports[0].path {
				source.WriteString("\n")
			}
			thirdParty = true
		}
		source.WriteString("\t")
		if generatedImport.name != "" {
			source.WriteString(generatedImport.name)
			source.WriteString(" ")
		}
		source.WriteString(strconv.Quote(generatedImport.path))
		source.WriteString("\n")
	}
	source.WriteString(")\n\n")
}

func (g *generator) positionError(pos token.Pos, formatString string, args ...any) error {
	position := g.pkg.Fset.Position(pos)
	if !position.IsValid() {
		return fmt.Errorf(formatString, args...)
	}
	return fmt.Errorf("%s: %s", position, fmt.Sprintf(formatString, args...))
}
