package main

import (
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"

	"golang.org/x/tools/go/packages"

	"github.com/oschwald/maxminddb-golang/v2/internal/maxminddbtag"
)

const (
	generatedPrefix = "// Code generated by maxminddb-gen"
	errorsPath      = "errors"
	fmtPath         = "fmt"
	mathPath        = "math"
	maxminddbTagKey = "maxminddb"
	mmdbdataPath    = "github.com/oschwald/maxminddb-golang/v2/mmdbdata"
)

type generator struct {
	structs         map[*types.Named]structInfo
	visiting        map[*types.Named]bool
	targetSet       map[*types.Named]bool
	generatedFiles  map[string]bool
	importPackages  map[string]*types.Package
	importNames     map[string]string
	pkg             *packages.Package
	unmarshaler     *types.Interface
	cursorDecoder   *types.Interface
	byteSlicePlan   *decodePlan
	helperNamespace string
	targets         []*types.Named
	nextID          int
	usesErrors      bool
	usesFmt         bool
	usesMath        bool
}

type structInfo struct {
	named  *types.Named
	fields []fieldInfo
}

type fieldInfo struct {
	plan        *decodePlan
	name        string
	goID        string
	maxSize     uint64
	maxSizeKind decodeKind
	hasMaxSize  bool
}

type methodKey struct {
	receiver string
	name     string
}

type priorGeneratedFile struct {
	file *ast.File
	path string
}

type decodeKind uint8

const (
	decodeBasic decodeKind = iota
	decodeBytes
	decodePointer
	decodeSlice
	decodeMap
	decodeStruct
	decodeUnmarshaler
	decodeCursorUnmarshaler
)

type decodePlan struct {
	typ     types.Type
	key     types.Type
	keyPlan *decodePlan
	basic   *types.Basic
	elem    *decodePlan
	named   *types.Named
	kind    decodeKind
}

func generatePackage(
	targetNames []string,
	output, buildConstraint string,
	diagnostics io.Writer,
) error {
	if diagnostics == nil {
		diagnostics = io.Discard
	}
	absOutput, err := filepath.Abs(output)
	if err != nil {
		return err
	}
	generatedFiles, err := findGeneratedFiles(absOutput)
	if err != nil {
		return err
	}
	liveTypes, handwrittenMethods, activeGeneratedFiles, typeAliases, err := loadPackageSyntax(
		generatedFiles,
		diagnostics,
	)
	if err != nil {
		return err
	}
	overlay, err := signatureOverlay(
		generatedFiles,
		liveTypes,
		handwrittenMethods,
		activeGeneratedFiles,
		typeAliases,
		nil,
	)
	if err != nil {
		return err
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo |
			packages.NeedTypesSizes,
		Overlay: overlay,
		Tests:   false,
	}
	pkgs, err := packages.Load(cfg, ".", mmdbdataPath)
	if err != nil {
		return err
	}
	if writePackageErrors(diagnostics, pkgs) != 0 {
		return errors.New("loading target package")
	}
	var targetPackage, mmdbdataPackage *packages.Package
	for _, loaded := range pkgs {
		if loaded.PkgPath == mmdbdataPath {
			mmdbdataPackage = loaded
		} else {
			targetPackage = loaded
		}
	}
	if targetPackage == nil || mmdbdataPackage == nil {
		return fmt.Errorf("loading target and %s packages", mmdbdataPath)
	}
	unmarshaler, err := packageInterface(mmdbdataPackage.Types, "Unmarshaler")
	if err != nil {
		return err
	}
	cursorDecoder, err := packageInterface(mmdbdataPackage.Types, "CursorUnmarshaler")
	if err != nil {
		return err
	}

	g := &generator{
		pkg:             targetPackage,
		structs:         make(map[*types.Named]structInfo),
		visiting:        make(map[*types.Named]bool),
		targetSet:       make(map[*types.Named]bool),
		generatedFiles:  generatedFileSet(generatedFiles),
		importPackages:  make(map[string]*types.Package),
		importNames:     make(map[string]string),
		unmarshaler:     unmarshaler,
		cursorDecoder:   cursorDecoder,
		helperNamespace: encodeHelperNamespace(absOutput),
	}
	if err := g.addTargets(targetNames, diagnostics); err != nil {
		return err
	}

	for _, target := range g.targets {
		if err := g.analyzeStruct(target); err != nil {
			return err
		}
	}
	if err := g.validateHelperNames(); err != nil {
		return err
	}
	g.prepareImports()
	source, err := g.render(buildConstraint)
	if err != nil {
		return err
	}
	if err := validateGeneratedPackage(
		absOutput,
		source,
		generatedFiles,
		liveTypes,
		handwrittenMethods,
		activeGeneratedFiles,
		typeAliases,
		diagnostics,
	); err != nil {
		return err
	}
	return writeAtomic(absOutput, source)
}

func (g *generator) addTargets(targetNames []string, diagnostics io.Writer) error {
	seenTargets := make(map[string]bool)
	for _, name := range targetNames {
		if seenTargets[name] {
			return fmt.Errorf("duplicate target type %q", name)
		}
		seenTargets[name] = true
		obj := g.pkg.Types.Scope().Lookup(name)
		if obj == nil {
			return fmt.Errorf("type %q is not declared in package %s", name, g.pkg.PkgPath)
		}
		typeName, ok := obj.(*types.TypeName)
		if !ok {
			return g.positionError(obj.Pos(), "%q is not a type", name)
		}
		named, ok := typeName.Type().(*types.Named)
		if !ok {
			return g.positionError(obj.Pos(), "%q is not a named type", name)
		}
		if _, ok := named.Underlying().(*types.Struct); !ok {
			return g.positionError(obj.Pos(), "target %s is not a struct", name)
		}
		if method := lookupUnmarshalMethod(named); method != nil && !g.isGeneratedMethod(method) {
			if g.implements(named, g.unmarshaler) {
				if _, err := fmt.Fprintf(
					diagnostics,
					"maxminddb-gen: skipping %s: handwritten UnmarshalMaxMindDB method\n",
					name,
				); err != nil {
					return err
				}
				continue
			}
			return g.positionError(
				method.Pos(),
				"type %s has an incompatible UnmarshalMaxMindDB method; want func(*mmdbdata.Decoder) error",
				name,
			)
		}
		if method := lookupCursorUnmarshalMethod(named); method != nil &&
			!g.isGeneratedMethod(method) {
			if g.implements(named, g.cursorDecoder) {
				if _, err := fmt.Fprintf(
					diagnostics,
					"maxminddb-gen: skipping %s: handwritten UnmarshalMaxMindDBCursor method\n",
					name,
				); err != nil {
					return err
				}
				continue
			}
			return g.positionError(
				method.Pos(),
				"type %s has an incompatible UnmarshalMaxMindDBCursor method; want func(mmdbdata.Cursor) (mmdbdata.Cursor, error)",
				name,
			)
		}
		if named.TypeParams().Len() != 0 {
			return g.positionError(obj.Pos(), "generic target %s is not supported", name)
		}
		g.targets = append(g.targets, named)
		g.targetSet[named] = true
	}
	if len(g.targets) == 0 {
		return errors.New("no decoders remain after excluding types with handwritten methods")
	}
	return nil
}

func findGeneratedFiles(path string) ([]priorGeneratedFile, error) {
	files := make([]priorGeneratedFile, 0)
	path = filepath.Clean(path)
	contents, err := os.ReadFile(path)
	if err == nil {
		file, generated, parseErr := parseGeneratedFile(path, contents)
		if parseErr != nil {
			return nil, parseErr
		}
		if !generated {
			return nil, fmt.Errorf("output %s exists and was not created by maxminddb-gen", path)
		}
		files = append(files, priorGeneratedFile{file: file, path: path})
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}

	cwd, err := os.Getwd()
	if err != nil {
		return nil, err
	}
	entries, err := os.ReadDir(cwd)
	if err != nil {
		return nil, err
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" ||
			strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		candidate := filepath.Clean(filepath.Join(cwd, entry.Name()))
		if candidate == path {
			continue
		}
		contents, err := os.ReadFile(candidate)
		if err != nil {
			return nil, err
		}
		if !strings.Contains(string(contents), generatedPrefix) {
			continue
		}
		file, generated, err := parseGeneratedFile(candidate, contents)
		if err != nil {
			return nil, err
		}
		if generated {
			files = append(files, priorGeneratedFile{file: file, path: candidate})
		}
	}
	return files, nil
}

func generatedFileSet(files []priorGeneratedFile) map[string]bool {
	paths := make(map[string]bool, len(files))
	for _, file := range files {
		paths[filepath.Clean(file.path)] = true
	}
	return paths
}

func loadPackageSyntax(
	generatedFiles []priorGeneratedFile,
	diagnostics io.Writer,
) (map[string]bool, map[methodKey]bool, map[string]bool, map[string]string, error) {
	overlay := make(map[string][]byte, len(generatedFiles))
	generatedPaths := make(map[string]bool, len(generatedFiles))
	for _, generated := range generatedFiles {
		overlay[generated.path] = packageStub(generated.file)
		generatedPaths[generated.path] = true
	}
	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax,
		Overlay: overlay,
		Tests:   false,
	}, ".")
	if err != nil {
		return nil, nil, nil, nil, err
	}
	if writePackageErrors(diagnostics, pkgs) != 0 || len(pkgs) != 1 {
		return nil, nil, nil, nil, errors.New("loading target package syntax")
	}

	typeSpecs := make(map[string]*ast.TypeSpec)
	rawHandwrittenMethods := make([]methodKey, 0)
	pkg := pkgs[0]
	activeGeneratedFiles := make(map[string]bool)
	for _, filename := range pkg.CompiledGoFiles {
		filename = filepath.Clean(filename)
		if generatedPaths[filename] {
			activeGeneratedFiles[filename] = true
		}
	}
	for _, file := range pkg.Syntax {
		filename := filepath.Clean(pkg.Fset.Position(file.Package).Filename)
		if generatedPaths[filename] {
			continue
		}
		for _, declaration := range file.Decls {
			switch declaration := declaration.(type) {
			case *ast.GenDecl:
				if declaration.Tok != token.TYPE {
					continue
				}
				for _, spec := range declaration.Specs {
					typeSpec := spec.(*ast.TypeSpec)
					typeSpecs[typeSpec.Name.Name] = typeSpec
				}
			case *ast.FuncDecl:
				receiver := receiverTypeName(declaration)
				if receiver != "" {
					rawHandwrittenMethods = append(rawHandwrittenMethods, methodKey{
						receiver: receiver,
						name:     declaration.Name.Name,
					})
				}
			default:
			}
		}
	}
	liveTypes, typeAliases := receiverTypes(typeSpecs)
	handwrittenMethods := make(map[methodKey]bool, len(rawHandwrittenMethods))
	for _, method := range rawHandwrittenMethods {
		method.receiver = canonicalTypeName(method.receiver, typeAliases)
		handwrittenMethods[method] = true
	}
	return liveTypes, handwrittenMethods, activeGeneratedFiles, typeAliases, nil
}

func receiverTypes(typeSpecs map[string]*ast.TypeSpec) (map[string]bool, map[string]string) {
	liveTypes := make(map[string]bool)
	typeAliases := make(map[string]string)
	for name := range typeSpecs {
		canonical, ok := receiverType(name, typeSpecs, make(map[string]bool))
		if !ok {
			continue
		}
		liveTypes[canonical] = true
		if name != canonical {
			typeAliases[name] = canonical
		}
	}
	return liveTypes, typeAliases
}

func receiverType(
	name string,
	typeSpecs map[string]*ast.TypeSpec,
	seen map[string]bool,
) (string, bool) {
	if seen[name] {
		return "", false
	}
	seen[name] = true
	typeSpec, ok := typeSpecs[name]
	if !ok || typeSpec.TypeParams != nil {
		return "", false
	}
	if !typeSpec.Assign.IsValid() {
		if !receiverUnderlyingType(typeSpec.Type, typeSpecs, seen) {
			return "", false
		}
		return name, true
	}
	target, ok := unparenthesized(typeSpec.Type).(*ast.Ident)
	if !ok {
		return "", false
	}
	return receiverType(target.Name, typeSpecs, seen)
}

func receiverUnderlyingType(
	expression ast.Expr,
	typeSpecs map[string]*ast.TypeSpec,
	seen map[string]bool,
) bool {
	switch expression := unparenthesized(expression).(type) {
	case *ast.ArrayType, *ast.ChanType, *ast.FuncType, *ast.MapType, *ast.StructType:
		return true
	case *ast.Ident:
		if valid, known := predeclaredReceiverUnderlying(expression.Name); known {
			return valid
		}
		return receiverDeclaredUnderlying(expression.Name, false, typeSpecs, seen)
	case *ast.IndexExpr:
		return receiverIndexedUnderlying(expression.X, typeSpecs, seen)
	case *ast.IndexListExpr:
		return receiverIndexedUnderlying(expression.X, typeSpecs, seen)
	case *ast.InterfaceType, *ast.StarExpr:
		return false
	default:
		return false
	}
}

func receiverIndexedUnderlying(
	expression ast.Expr,
	typeSpecs map[string]*ast.TypeSpec,
	seen map[string]bool,
) bool {
	identifier, ok := unparenthesized(expression).(*ast.Ident)
	if !ok {
		return false
	}
	return receiverDeclaredUnderlying(identifier.Name, true, typeSpecs, seen)
}

func receiverDeclaredUnderlying(
	name string,
	instantiated bool,
	typeSpecs map[string]*ast.TypeSpec,
	seen map[string]bool,
) bool {
	if seen[name] {
		return false
	}
	typeSpec, ok := typeSpecs[name]
	if !ok || typeSpec.TypeParams != nil && !instantiated {
		return false
	}
	seen[name] = true
	return receiverUnderlyingType(typeSpec.Type, typeSpecs, seen)
}

func predeclaredReceiverUnderlying(name string) (valid, known bool) {
	switch name {
	case "bool", "byte", "complex64", "complex128", "float32", "float64",
		"int", "int8", "int16", "int32", "int64", "rune", "string",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr":
		return true, true
	case "any", "comparable", "error":
		return false, true
	default:
		return false, false
	}
}

func unparenthesized(expression ast.Expr) ast.Expr {
	for {
		parenthesized, ok := expression.(*ast.ParenExpr)
		if !ok {
			return expression
		}
		expression = parenthesized.X
	}
}

func signatureOverlay(
	generatedFiles []priorGeneratedFile,
	liveTypes map[string]bool,
	handwrittenMethods map[methodKey]bool,
	activeGeneratedFiles map[string]bool,
	typeAliases map[string]string,
	includedMethods map[methodKey]bool,
) (map[string][]byte, error) {
	overlay := make(map[string][]byte, len(generatedFiles))
	if includedMethods == nil {
		includedMethods = make(map[methodKey]bool)
	}
	for _, generated := range generatedFiles {
		if !activeGeneratedFiles[generated.path] {
			overlay[generated.path] = packageStub(generated.file)
			continue
		}
		methods := make([]*ast.FuncDecl, 0)
		for _, declaration := range generated.file.Decls {
			method, key, ok := exportedMethodKey(declaration, typeAliases)
			if !ok {
				continue
			}
			if !liveTypes[key.receiver] || handwrittenMethods[key] || includedMethods[key] {
				continue
			}
			methods = append(methods, method)
			includedMethods[key] = true
		}
		stub, err := signatureStub(generated.file, methods)
		if err != nil {
			return nil, err
		}
		overlay[generated.path] = stub
	}
	return overlay, nil
}

func receiverTypeName(method *ast.FuncDecl) string {
	if method.Recv == nil || len(method.Recv.List) != 1 {
		return ""
	}
	return baseTypeName(method.Recv.List[0].Type)
}

func baseTypeName(expression ast.Expr) string {
	switch expression := expression.(type) {
	case *ast.Ident:
		return expression.Name
	case *ast.StarExpr:
		return baseTypeName(expression.X)
	case *ast.IndexExpr:
		return baseTypeName(expression.X)
	case *ast.IndexListExpr:
		return baseTypeName(expression.X)
	default:
		return ""
	}
}

func canonicalTypeName(name string, aliases map[string]string) string {
	seen := make(map[string]bool)
	for {
		if seen[name] {
			return name
		}
		seen[name] = true
		next, ok := aliases[name]
		if !ok {
			return name
		}
		name = next
	}
}

func parseGeneratedFile(path string, contents []byte) (*ast.File, bool, error) {
	file, err := parser.ParseFile(
		token.NewFileSet(),
		path,
		contents,
		parser.ParseComments,
	)
	if err != nil {
		return nil, false, fmt.Errorf("reading package from prior output: %w", err)
	}
	for _, group := range file.Comments {
		if group.Pos() > file.Package {
			break
		}
		for _, comment := range group.List {
			if isGeneratedMarker(comment.Text) {
				return file, true, nil
			}
		}
	}
	return file, false, nil
}

func isGeneratedMarker(comment string) bool {
	const suffix = "; DO NOT EDIT."
	if comment == generatedPrefix+suffix {
		return true
	}
	prefix := generatedPrefix + " "
	if !strings.HasPrefix(comment, prefix) || !strings.HasSuffix(comment, suffix) {
		return false
	}
	version := comment[len(prefix) : len(comment)-len(suffix)]
	return version != "" && !strings.ContainsAny(version, " \t\r\n")
}

func packageStub(file *ast.File) []byte {
	return []byte(generatedBuildConstraints(file) + "package " + file.Name.Name + "\n")
}

func signatureStub(file *ast.File, methods []*ast.FuncDecl) ([]byte, error) {
	if len(methods) == 0 {
		return packageStub(file), nil
	}

	usedImports := make(map[string]bool)
	for _, method := range methods {
		for _, node := range []ast.Node{method.Recv, method.Type} {
			ast.Inspect(node, func(node ast.Node) bool {
				selector, ok := node.(*ast.SelectorExpr)
				if !ok {
					return true
				}
				identifier, ok := selector.X.(*ast.Ident)
				if ok {
					usedImports[identifier.Name] = true
				}
				return true
			})
		}
	}

	var source strings.Builder
	source.WriteString(generatedBuildConstraints(file))
	fmt.Fprintf(&source, "package %s\n\n", file.Name.Name)
	imports := make([]*ast.ImportSpec, 0)
	for _, imported := range file.Imports {
		name, err := generatedImportName(imported)
		if err != nil {
			return nil, err
		}
		if usedImports[name] {
			imports = append(imports, imported)
		}
	}
	if len(imports) > 0 {
		source.WriteString("import (\n")
		for _, imported := range imports {
			source.WriteByte('\t')
			if err := format.Node(&source, token.NewFileSet(), imported); err != nil {
				return nil, err
			}
			source.WriteByte('\n')
		}
		source.WriteString(")\n\n")
	}
	for _, method := range methods {
		stub := *method
		stub.Doc = nil
		stub.Body = &ast.BlockStmt{List: []ast.Stmt{&ast.ExprStmt{X: &ast.CallExpr{
			Fun: ast.NewIdent("panic"),
			Args: []ast.Expr{&ast.BasicLit{
				Kind:  token.STRING,
				Value: strconv.Quote("maxminddb-gen loading stub"),
			}},
		}}}}
		if err := format.Node(&source, token.NewFileSet(), &stub); err != nil {
			return nil, err
		}
		source.WriteString("\n\n")
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting prior generated signatures: %w", err)
	}
	return formatted, nil
}

func generatedImportName(imported *ast.ImportSpec) (string, error) {
	if imported.Name != nil {
		return imported.Name.Name, nil
	}
	path, err := strconv.Unquote(imported.Path.Value)
	if err != nil {
		return "", err
	}
	if path == mmdbdataPath {
		return "mmdbdata", nil
	}
	return filepath.Base(path), nil
}

func generatedBuildConstraints(file *ast.File) string {
	var constraints strings.Builder
	for _, group := range file.Comments {
		if group.Pos() > file.Package {
			break
		}
		for _, comment := range group.List {
			if strings.HasPrefix(comment.Text, "//go:build ") ||
				strings.HasPrefix(comment.Text, "// +build ") {
				constraints.WriteString(comment.Text)
				constraints.WriteByte('\n')
			}
		}
	}
	if constraints.Len() > 0 {
		constraints.WriteByte('\n')
	}
	return constraints.String()
}

func validateGeneratedPackage(
	path string,
	source []byte,
	generatedFiles []priorGeneratedFile,
	liveTypes map[string]bool,
	handwrittenMethods map[methodKey]bool,
	activeGeneratedFiles map[string]bool,
	typeAliases map[string]string,
	diagnostics io.Writer,
) error {
	file, generated, err := parseGeneratedFile(path, source)
	if err != nil {
		return err
	}
	if !generated {
		return errors.New("rendered output is missing its generated-code marker")
	}

	remainingFiles := make([]priorGeneratedFile, 0, len(generatedFiles))
	for _, existing := range generatedFiles {
		if existing.path != path {
			remainingFiles = append(remainingFiles, existing)
		}
	}
	overlay, err := signatureOverlay(
		remainingFiles,
		liveTypes,
		handwrittenMethods,
		activeGeneratedFiles,
		typeAliases,
		generatedMethodKeys(file, typeAliases),
	)
	if err != nil {
		return err
	}
	overlay[path] = source

	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo |
			packages.NeedTypesSizes,
		Overlay: overlay,
		Tests:   false,
	}, ".")
	if err != nil {
		return err
	}
	if writePackageErrors(diagnostics, pkgs) != 0 || len(pkgs) != 1 {
		return errors.New("validating generated package")
	}
	return nil
}

func writePackageErrors(diagnostics io.Writer, pkgs []*packages.Package) int {
	if diagnostics == nil {
		diagnostics = io.Discard
	}
	count := 0
	for _, pkg := range pkgs {
		for _, err := range pkg.Errors {
			_, _ = fmt.Fprintln(diagnostics, err)
			count++
		}
	}
	return count
}

func generatedMethodKeys(file *ast.File, typeAliases map[string]string) map[methodKey]bool {
	methods := make(map[methodKey]bool)
	for _, declaration := range file.Decls {
		_, key, ok := exportedMethodKey(declaration, typeAliases)
		if !ok {
			continue
		}
		methods[key] = true
	}
	return methods
}

func exportedMethodKey(
	declaration ast.Decl,
	typeAliases map[string]string,
) (*ast.FuncDecl, methodKey, bool) {
	method, ok := declaration.(*ast.FuncDecl)
	if !ok || method.Recv == nil || !method.Name.IsExported() {
		return nil, methodKey{}, false
	}
	return method, methodKey{
		receiver: canonicalTypeName(receiverTypeName(method), typeAliases),
		name:     method.Name.Name,
	}, true
}

type atomicOutputFile interface {
	Name() string
	Write([]byte) (int, error)
	Chmod(os.FileMode) error
	Sync() error
	Close() error
}

func writeAtomic(path string, contents []byte) error {
	return writeAtomicWith(
		path,
		contents,
		func(dir, pattern string) (atomicOutputFile, error) {
			return os.CreateTemp(dir, pattern)
		},
		replaceFile,
	)
}

func writeAtomicWith(
	path string,
	contents []byte,
	createTemp func(string, string) (atomicOutputFile, error),
	replace func(string, string) error,
) error {
	dir := filepath.Dir(path)
	temp, err := createTemp(dir, ".maxminddb-gen-*")
	if err != nil {
		return err
	}
	tempName := temp.Name()
	defer func() { _ = os.Remove(tempName) }()
	if _, err := temp.Write(contents); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Chmod(0o644); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Sync(); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	return replace(tempName, path)
}

func (g *generator) analyzeStruct(named *types.Named) error {
	if named.TypeParams().Len() != 0 {
		return g.positionError(
			named.Obj().Pos(),
			"generic struct %s is not supported",
			named.Obj().Name(),
		)
	}
	if _, ok := g.structs[named]; ok {
		return nil
	}
	if g.visiting[named] {
		return g.positionError(
			named.Obj().Pos(),
			"recursive type graph through %s is not supported",
			named.Obj().Name(),
		)
	}
	g.visiting[named] = true
	defer delete(g.visiting, named)

	structure := named.Underlying().(*types.Struct)
	info := structInfo{named: named}
	seenNames := make(map[string]token.Pos)
	for i := range structure.NumFields() {
		field := structure.Field(i)
		if field.Embedded() {
			return g.positionError(
				field.Pos(),
				"embedded field %s is not yet supported",
				field.Name(),
			)
		}
		if !field.Exported() {
			continue
		}
		tag, tagged, err := maxminddbTag(structure.Tag(i))
		if err != nil {
			return g.positionError(field.Pos(), "field %s: %v", field.Name(), err)
		}
		if tag.Ignored {
			continue
		}
		name := field.Name()
		if tagged && tag.HasName {
			name = tag.Name
		}
		if previous, exists := seenNames[name]; exists {
			return g.positionError(
				field.Pos(),
				"field %s conflicts with another field at %s for MMDB key %q",
				field.Name(),
				g.pkg.Fset.Position(previous),
				name,
			)
		}
		seenNames[name] = field.Pos()
		plan, err := g.analyzeType(field.Type())
		if err != nil {
			return g.positionError(field.Pos(), "field %s: %v", field.Name(), err)
		}
		maxSizeKind, maxSizeSupported := maxSizeKindForPlan(plan)
		if tag.HasMaxSize && !maxSizeSupported {
			return g.positionError(
				field.Pos(),
				"field %s: maxsize is only supported for maps, slices, strings, and bytes",
				field.Name(),
			)
		}
		info.fields = append(
			info.fields,
			fieldInfo{
				plan:        plan,
				name:        name,
				goID:        field.Name(),
				maxSize:     tag.MaxSize,
				maxSizeKind: maxSizeKind,
				hasMaxSize:  tag.HasMaxSize,
			},
		)
	}
	g.structs[named] = info
	return nil
}

func (g *generator) analyzeType(t types.Type) (*decodePlan, error) {
	if pointer, ok := t.(*types.Pointer); ok {
		elem, err := g.analyzeType(pointer.Elem())
		return &decodePlan{typ: t, kind: decodePointer, elem: elem}, err
	}
	if _, ok := t.Underlying().(*types.Interface); ok {
		return nil, fmt.Errorf("interface type %s is not supported", t)
	}
	if g.implements(t, g.cursorDecoder) {
		return &decodePlan{typ: t, kind: decodeCursorUnmarshaler}, nil
	}
	if g.implements(t, g.unmarshaler) {
		return &decodePlan{typ: t, kind: decodeUnmarshaler}, nil
	}
	switch value := t.(type) {
	case *types.Named:
		underlying := value.Underlying()
		if _, ok := underlying.(*types.Struct); ok {
			if value.Origin().TypeParams().Len() != 0 {
				return nil, fmt.Errorf("generic struct %s is not supported", value.Obj().Name())
			}
			if value.Obj().Pkg() != g.pkg.Types {
				return nil, fmt.Errorf(
					"struct type %s is owned by another package and does not implement mmdbdata.CursorUnmarshaler or mmdbdata.Unmarshaler",
					value,
				)
			}
			if err := g.analyzeStruct(value); err != nil {
				return nil, err
			}
			return &decodePlan{typ: t, kind: decodeStruct, named: value}, nil
		}
		if basic, ok := underlying.(*types.Basic); ok {
			if err := supportedBasic(basic); err != nil {
				return nil, err
			}
			return &decodePlan{typ: t, kind: decodeBasic, basic: basic}, nil
		}
		if g.visiting[value] {
			return nil, fmt.Errorf(
				"recursive type graph through %s is not supported",
				value.Obj().Name(),
			)
		}
		g.visiting[value] = true
		defer delete(g.visiting, value)
		plan, err := g.analyzeType(underlying)
		if plan != nil && plan.kind == decodeBytes {
			plan = &decodePlan{typ: t, kind: decodeSlice, elem: plan.elem}
		} else if plan != nil {
			plan.typ = t
		}
		return plan, err
	case *types.Basic:
		if err := supportedBasic(value); err != nil {
			return nil, err
		}
		return &decodePlan{typ: t, kind: decodeBasic, basic: value}, nil
	case *types.Slice:
		if types.Identical(t, types.NewSlice(types.Typ[types.Byte])) {
			elem, err := g.analyzeType(value.Elem())
			return &decodePlan{typ: t, kind: decodeBytes, elem: elem}, err
		}
		elem, err := g.analyzeType(value.Elem())
		return &decodePlan{typ: t, kind: decodeSlice, elem: elem}, err
	case *types.Map:
		key, ok := value.Key().Underlying().(*types.Basic)
		if !ok || key.Kind() != types.String {
			return nil, fmt.Errorf("map key type must be string, found %s", value.Key())
		}
		var keyPlan *decodePlan
		if g.implements(value.Key(), g.cursorDecoder) {
			keyPlan = &decodePlan{typ: value.Key(), kind: decodeCursorUnmarshaler}
		} else if g.implements(value.Key(), g.unmarshaler) {
			keyPlan = &decodePlan{typ: value.Key(), kind: decodeUnmarshaler}
		}
		elem, err := g.analyzeType(value.Elem())
		return &decodePlan{
			typ: t, kind: decodeMap, key: value.Key(), keyPlan: keyPlan, elem: elem,
		}, err
	default:
		return nil, fmt.Errorf("unsupported type %s", t)
	}
}

func supportedBasic(basic *types.Basic) error {
	switch basic.Kind() {
	case types.Bool, types.String,
		types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
		types.Float32, types.Float64:
		return nil
	default:
		return fmt.Errorf("unsupported type %s", basic)
	}
}

func maxminddbTag(raw string) (maxminddbtag.Options, bool, error) {
	for raw != "" {
		i := 0
		for i < len(raw) && raw[i] == ' ' {
			i++
		}
		raw = raw[i:]
		if raw == "" {
			break
		}

		i = 0
		for i < len(raw) && raw[i] > ' ' && raw[i] != ':' && raw[i] != '"' && raw[i] != 0x7f {
			i++
		}
		if i == 0 || i+1 >= len(raw) || raw[i] != ':' || raw[i+1] != '"' {
			if raw[:i] == maxminddbTagKey {
				return maxminddbtag.Options{}, false, errors.New(
					"malformed maxminddb struct tag",
				)
			}
			next := strings.IndexByte(raw, ' ')
			if next < 0 {
				break
			}
			raw = raw[next+1:]
			continue
		}
		name := raw[:i]
		raw = raw[i+1:]

		i = 1
		for i < len(raw) && raw[i] != '"' {
			if raw[i] == '\\' {
				i++
			}
			i++
		}
		if i >= len(raw) {
			if name == maxminddbTagKey {
				return maxminddbtag.Options{}, false, errors.New(
					"unterminated maxminddb struct tag",
				)
			}
			break
		}
		quotedValue := raw[:i+1]
		raw = raw[i+1:]
		if name != maxminddbTagKey {
			continue
		}
		if !utf8.ValidString(quotedValue) {
			return maxminddbtag.Options{}, false, errors.New(
				"invalid UTF-8 maxminddb struct tag",
			)
		}
		value, err := strconv.Unquote(quotedValue)
		if err != nil {
			return maxminddbtag.Options{}, false, fmt.Errorf(
				"invalid maxminddb struct tag: %w",
				err,
			)
		}
		if !utf8.ValidString(value) {
			return maxminddbtag.Options{}, false, errors.New(
				"invalid UTF-8 maxminddb struct tag",
			)
		}
		options, err := maxminddbtag.Parse(value)
		if err != nil {
			return maxminddbtag.Options{}, false, fmt.Errorf(
				"invalid maxminddb struct tag: %w",
				err,
			)
		}
		return options, true, nil
	}
	return maxminddbtag.Options{}, false, nil
}

func maxSizeKindForPlan(plan *decodePlan) (decodeKind, bool) {
	for plan.kind == decodePointer {
		plan = plan.elem
	}
	switch plan.kind {
	case decodeBytes, decodeSlice, decodeMap:
		return plan.kind, true
	case decodeBasic:
		if plan.basic.Kind() == types.String {
			return decodeBasic, true
		}
	case decodeCursorUnmarshaler, decodeUnmarshaler:
		return maxSizeKindForType(plan.typ)
	default:
	}
	return 0, false
}

func isCustomUnmarshalerPlan(plan *decodePlan) bool {
	for plan.kind == decodePointer {
		plan = plan.elem
	}
	return plan.kind == decodeCursorUnmarshaler || plan.kind == decodeUnmarshaler
}

func maxSizeKindForType(t types.Type) (decodeKind, bool) {
	for {
		pointer, ok := t.(*types.Pointer)
		if !ok {
			break
		}
		t = pointer.Elem()
	}
	switch underlying := t.Underlying().(type) {
	case *types.Basic:
		if underlying.Kind() == types.String {
			return decodeBasic, true
		}
	case *types.Map:
		return decodeMap, true
	case *types.Slice:
		if types.Identical(t, types.NewSlice(types.Typ[types.Byte])) {
			return decodeBytes, true
		}
		return decodeSlice, true
	default:
	}
	return 0, false
}

func lookupUnmarshalMethod(named *types.Named) *types.Func {
	return lookupMethod(named, "UnmarshalMaxMindDB")
}

func lookupCursorUnmarshalMethod(named *types.Named) *types.Func {
	return lookupMethod(named, "UnmarshalMaxMindDBCursor")
}

func lookupMethod(named *types.Named, name string) *types.Func {
	selection := types.NewMethodSet(types.NewPointer(named)).Lookup(nil, name)
	if selection == nil {
		return nil
	}
	method, _ := selection.Obj().(*types.Func)
	return method
}

func packageInterface(pkg *types.Package, name string) (*types.Interface, error) {
	object := pkg.Scope().Lookup(name)
	if object == nil {
		return nil, fmt.Errorf("%s does not declare %s", pkg.Path(), name)
	}
	iface, ok := object.Type().Underlying().(*types.Interface)
	if !ok {
		return nil, fmt.Errorf("%s.%s is not an interface", pkg.Path(), name)
	}
	return iface.Complete(), nil
}

func (g *generator) implements(t types.Type, iface *types.Interface) bool {
	named := t
	if pointer, ok := named.(*types.Pointer); ok {
		named = pointer.Elem()
	}
	if named, ok := named.(*types.Named); ok && named.Obj().Pkg() == g.pkg.Types {
		var method *types.Func
		switch iface {
		case g.unmarshaler:
			method = lookupUnmarshalMethod(named)
		case g.cursorDecoder:
			method = lookupCursorUnmarshalMethod(named)
		default:
		}
		if g.isGeneratedMethod(method) {
			return false
		}
	}
	if types.Implements(t, iface) {
		return true
	}
	if _, ok := t.(*types.Pointer); ok {
		return false
	}
	return types.Implements(types.NewPointer(t), iface)
}

func (g *generator) isGeneratedMethod(method *types.Func) bool {
	if method == nil {
		return false
	}
	filename := filepath.Clean(g.pkg.Fset.Position(method.Pos()).Filename)
	return g.generatedFiles[filename]
}

func encodeHelperNamespace(output string) string {
	const hex = "0123456789abcdef"
	stem := strings.TrimSuffix(filepath.Base(output), filepath.Ext(output))
	var encoded strings.Builder
	for i := range len(stem) {
		value := stem[i]
		if value >= 'a' && value <= 'z' || value >= 'A' && value <= 'Z' ||
			value >= '0' && value <= '9' {
			encoded.WriteByte(value)
			continue
		}
		encoded.WriteByte('_')
		encoded.WriteByte(hex[value>>4])
		encoded.WriteByte(hex[value&0x0f])
	}
	return encoded.String()
}

func (g *generator) helperName(named *types.Named) string {
	if g.targetSet[named] {
		return "maxminddbGenDecode" + named.Obj().Name()
	}
	return "maxminddbGen_" + g.helperNamespace + "_Decode" + named.Obj().Name()
}

func (g *generator) validateHelperNames() error {
	reserved := make(map[string]struct{}, len(g.structs)+2)
	reserve := func(name string, pos token.Pos) error {
		if _, ok := reserved[name]; ok {
			return fmt.Errorf("generated helper %s collides with another generated helper", name)
		}
		reserved[name] = struct{}{}
		if g.pkg.Types.Scope().Lookup(name) == nil {
			return nil
		}
		if pos.IsValid() {
			return g.positionError(
				pos,
				"generated helper %s collides with an existing declaration",
				name,
			)
		}
		return fmt.Errorf("generated helper %s collides with an existing declaration", name)
	}

	namedTypes := make([]*types.Named, 0, len(g.structs))
	for named := range g.structs {
		namedTypes = append(namedTypes, named)
	}
	slices.SortFunc(namedTypes, func(a, b *types.Named) int {
		return strings.Compare(a.Obj().Name(), b.Obj().Name())
	})
	for _, named := range namedTypes {
		if err := reserve(g.helperName(named), named.Obj().Pos()); err != nil {
			return err
		}
	}
	for _, info := range g.structs {
		for _, field := range info.fields {
			if plan := findDecodeBytesPlan(field.plan); plan != nil {
				g.byteSlicePlan = plan
				break
			}
		}
		if g.byteSlicePlan != nil {
			break
		}
	}
	if g.byteSlicePlan != nil {
		for _, name := range []string{g.bytesHelperName(), g.byteSliceHelperName()} {
			if err := reserve(name, token.NoPos); err != nil {
				return err
			}
		}
	}
	return nil
}

func findDecodeBytesPlan(plan *decodePlan) *decodePlan {
	if plan.kind == decodeBytes {
		return plan
	}
	switch plan.kind {
	case decodePointer, decodeSlice, decodeMap:
		return findDecodeBytesPlan(plan.elem)
	default:
		return nil
	}
}

func (g *generator) byteSliceHelperName() string {
	return "maxminddbGen_" + g.helperNamespace + "_ByteSlice"
}

func (g *generator) bytesHelperName() string {
	return "maxminddbGen_" + g.helperNamespace + "_Bytes"
}

func (g *generator) render(buildConstraint string) ([]byte, error) {
	var body strings.Builder
	mmdbdata := g.importNames[mmdbdataPath]
	infos := make([]structInfo, 0, len(g.structs))
	for _, info := range g.structs {
		infos = append(infos, info)
	}
	slices.SortFunc(infos, func(a, b structInfo) int {
		return strings.Compare(a.named.Obj().Name(), b.named.Obj().Name())
	})
	for _, info := range infos {
		g.emitStruct(&body, info)
	}
	if g.byteSlicePlan != nil {
		g.emitByteSliceHelper(&body)
	}
	for _, target := range g.targets {
		fmt.Fprintf(
			&body,
			"func (out *%s) UnmarshalMaxMindDBCursor(cursor %s.Cursor) (%s.Cursor, error) {\n",
			target.Obj().Name(),
			mmdbdata,
			mmdbdata,
		)
		fmt.Fprintf(&body, "\treturn %s(cursor, out)\n", g.helperName(target))
		body.WriteString("}\n\n")

		fmt.Fprintf(
			&body,
			"func (out *%s) UnmarshalMaxMindDB(decoder *%s.Decoder) error {\n",
			target.Obj().Name(),
			mmdbdata,
		)
		fmt.Fprintf(&body, "\tnext, err := %s(decoder.Cursor(), out)\n", g.helperName(target))
		body.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
		body.WriteString("\treturn decoder.Advance(next)\n}\n\n")
	}

	var source strings.Builder
	if buildConstraint != "" {
		fmt.Fprintf(&source, "//go:build %s\n\n", buildConstraint)
	}
	fmt.Fprintf(&source, "%s; DO NOT EDIT.\n", generatedPrefix)
	fmt.Fprintf(
		&source,
		"// Requires github.com/oschwald/maxminddb-golang/v2 %s or newer.\n\n",
		minimumLibrary,
	)
	fmt.Fprintf(&source, "package %s\n\n", g.pkg.Name)
	g.emitImports(&source)
	source.WriteString(body.String())
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w\n%s", err, source.String())
	}
	return formatted, nil
}

func (g *generator) emitStruct(out *strings.Builder, info structInfo) {
	mmdbdata := g.importNames[mmdbdataPath]
	fmt.Fprintf(
		out,
		"func %s(cursor %s.Cursor, out *%s) (%s.Cursor, error) {\n",
		g.helperName(info.named),
		mmdbdata,
		info.named.Obj().Name(),
		mmdbdata,
	)
	out.WriteString("\tentries, err := cursor.MapReader()\n")
	fmt.Fprintf(
		out,
		"\tif err != nil {\n\t\treturn %s.Cursor{}, %s.NormalizeUnmarshalError[%s](err)\n\t}\n",
		mmdbdata,
		mmdbdata,
		info.named.Obj().Name(),
	)
	out.WriteString("\tnext := entries.First()\n")
	if len(info.fields) != 0 {
		if len(info.fields) <= 64 {
			out.WriteString("\tvar seenFields uint64\n")
		} else {
			fmt.Fprintf(out, "\tvar seenFields [%d]uint64\n", (len(info.fields)+63)/64)
		}
	}
	out.WriteString("\tfor range entries.Len() {\n")
	out.WriteString("\t\tkey, valueCursor, keyErr := next.ReadMapKey()\n")
	fmt.Fprintf(
		out,
		"\t\tif keyErr != nil {\n\t\t\treturn %s.Cursor{}, keyErr\n\t\t}\n",
		mmdbdata,
	)
	out.WriteString("\t\tswitch string(key) {\n")
	for fieldIndex, field := range info.fields {
		fmt.Fprintf(out, "\t\tcase %s:\n", strconv.Quote(field.name))
		seenField := "seenFields"
		if len(info.fields) > 64 {
			seenField = fmt.Sprintf("seenFields[%d]", fieldIndex/64)
		}
		fieldBit := uint64(1) << (fieldIndex % 64)
		fmt.Fprintf(out, "\t\t\tif %s&%d != 0 {\n", seenField, fieldBit)
		fmt.Fprintf(
			out,
			"\t\t\t\treturn %s.Cursor{}, %s.NewInvalidDatabaseError(\"duplicate map key %%q\", key)\n",
			mmdbdata,
			mmdbdata,
		)
		out.WriteString("\t\t\t}\n")
		fmt.Fprintf(out, "\t\t\t%s |= %d\n", seenField, fieldBit)
		if field.hasMaxSize {
			if !g.emitMaxSizeDecode(
				out,
				field.plan,
				"valueCursor",
				"out."+field.goID,
				"next",
				"err",
				3,
				field.maxSize,
			) {
				fmt.Fprintf(
					out,
					"\t\t\tif err = valueCursor.CheckMaxSize(%s, %d); err == nil {\n",
					g.maxSizeKindExpression(field.plan, field.maxSizeKind),
					field.maxSize,
				)
				g.emitDecode(out, field.plan, "valueCursor", "out."+field.goID, "next", "err", 4)
				out.WriteString("\t\t\t}\n")
			}
		} else {
			g.emitDecode(out, field.plan, "valueCursor", "out."+field.goID, "next", "err", 3)
		}
		errorFormat := "decoding field " + strings.ReplaceAll(field.name, "%", "%%") + ": %w"
		fmt.Fprintf(
			out,
			"\t\t\tif err != nil {\n\t\t\t\treturn %s.Cursor{}, %s.Errorf(%s, %s)\n\t\t\t}\n",
			mmdbdata,
			g.importNames[fmtPath],
			strconv.Quote(errorFormat),
			g.errorExpression(field.plan, "err"),
		)
	}
	out.WriteString("\t\tdefault:\n\t\t\tnext, err = valueCursor.Skip()\n\t\t}\n")
	fmt.Fprintf(
		out,
		"\t\tif err != nil {\n\t\t\treturn %s.Cursor{}, err\n\t\t}\n",
		mmdbdata,
	)
	out.WriteString("\t}\n")
	out.WriteString("\treturn entries.End(next)\n}\n\n")
}

func (g *generator) emitMaxSizeDecode(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
	maximum uint64,
) bool {
	switch {
	case plan.kind == decodeBasic && plan.basic.Kind() == types.String:
		pad := strings.Repeat("\t", indent)
		id := g.id()
		fmt.Fprintf(
			out,
			"%svar value%d string\n%svalue%d, %s, %s = %s.ReadStringMaxSize(%d)\n",
			pad,
			id,
			pad,
			id,
			next,
			errName,
			cursor,
			maximum,
		)
		fmt.Fprintf(
			out,
			"%sif %s == nil {\n%s\t%s = %s(value%d)\n%s}\n",
			pad,
			errName,
			pad,
			target,
			g.typeString(plan.typ),
			id,
			pad,
		)
		return true
	case plan.kind == decodeSlice:
		g.emitSliceMaxSize(out, plan, cursor, target, next, errName, indent, maximum)
		return true
	default:
		return false
	}
}

func (g *generator) maxSizeKindExpression(plan *decodePlan, kind decodeKind) string {
	mmdbdata := g.importNames[mmdbdataPath]
	if isCustomUnmarshalerPlan(plan) {
		// A custom callback may consume any MMDB encoding regardless of its Go
		// type's underlying shape, so constrain every size-bearing input kind.
		return mmdbdata + ".NewKindSet(" +
			mmdbdata + ".KindMap, " +
			mmdbdata + ".KindSlice, " +
			mmdbdata + ".KindString, " +
			mmdbdata + ".KindBytes)"
	}
	switch kind {
	case decodeBasic:
		return mmdbdata + ".NewKindSet(" + mmdbdata + ".KindString)"
	case decodeBytes:
		return mmdbdata + ".NewKindSet(" + mmdbdata + ".KindBytes, " +
			mmdbdata + ".KindSlice)"
	case decodeSlice:
		return mmdbdata + ".NewKindSet(" + mmdbdata + ".KindSlice)"
	case decodeMap:
		return mmdbdata + ".NewKindSet(" + mmdbdata + ".KindMap)"
	default:
		panic("unsupported maxsize decode kind")
	}
}

func (g *generator) emitDecode(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
) {
	pad := strings.Repeat("\t", indent)
	switch plan.kind {
	case decodePointer:
		id := g.id()
		fmt.Fprintf(out, "%sif %s == nil {\n", pad, target)
		fmt.Fprintf(out, "%s\tvar decoded%d %s\n", pad, id, g.typeString(plan.elem.typ))
		g.emitDecode(
			out,
			plan.elem,
			cursor,
			fmt.Sprintf("decoded%d", id),
			next,
			errName,
			indent+1,
		)
		fmt.Fprintf(
			out,
			"%s\tif %s == nil {\n%s\t\t%s = &decoded%d\n%s\t}\n",
			pad,
			errName,
			pad,
			target,
			id,
			pad,
		)
		fmt.Fprintf(out, "%s} else {\n", pad)
		g.emitDecode(
			out,
			plan.elem,
			cursor,
			fmt.Sprintf("(*%s)", target),
			next,
			errName,
			indent+1,
		)
		fmt.Fprintf(out, "%s}\n", pad)
	case decodeCursorUnmarshaler:
		fmt.Fprintf(
			out,
			"%s%s, %s = %s.UnmarshalCursor(&%s)\n",
			pad,
			next,
			errName,
			cursor,
			target,
		)
	case decodeUnmarshaler:
		fmt.Fprintf(out, "%s%s, %s = %s.Unmarshal(&%s)\n", pad, next, errName, cursor, target)
	case decodeStruct:
		fmt.Fprintf(
			out,
			"%s%s, %s = %s(%s, &%s)\n",
			pad,
			next,
			errName,
			g.helperName(plan.named),
			cursor,
			target,
		)
	case decodeBasic:
		g.emitBasic(out, plan.typ, plan.basic, cursor, target, next, errName, indent)
	case decodeBytes:
		g.emitBytes(out, cursor, target, next, errName, indent)
	case decodeSlice:
		g.emitSlice(out, plan, cursor, target, next, errName, indent)
	case decodeMap:
		g.emitMap(out, plan, cursor, target, next, errName, indent)
	default:
		panic("unsupported decode plan for " + plan.typ.String())
	}
}

func (g *generator) emitBytes(
	out *strings.Builder,
	cursor, target, next, errName string,
	indent int,
) {
	pad := strings.Repeat("\t", indent)
	fmt.Fprintf(
		out,
		"%s%s, %s, %s = %s(%s, %s)\n",
		pad,
		target,
		next,
		errName,
		g.bytesHelperName(),
		cursor,
		target,
	)
}

func (g *generator) emitByteSliceHelper(out *strings.Builder) {
	mmdbdata := g.importNames[mmdbdataPath]
	fmt.Fprintf(
		out,
		"func %s(cursor %s.Cursor, target []byte) ([]byte, %s.Cursor, error) {\n",
		g.bytesHelperName(),
		mmdbdata,
		mmdbdata,
	)
	out.WriteString("\tdecoded, next, err := cursor.ReadBytes()\n")
	fmt.Fprintf(
		out,
		"\tif err != nil {\n\t\treturn %s(cursor, target, err)\n\t}\n",
		g.byteSliceHelperName(),
	)
	out.WriteString(
		"\tif len(decoded) == 0 && target == nil {\n\t\treturn []byte{}, next, nil\n\t}\n",
	)
	out.WriteString("\treturn append(target[:0], decoded...), next, nil\n}\n\n")
	fmt.Fprintf(
		out,
		"func %s(cursor %s.Cursor, target []byte, readErr error) ([]byte, %s.Cursor, error) {\n",
		g.byteSliceHelperName(),
		mmdbdata,
		mmdbdata,
	)
	fmt.Fprintf(out, "\tvar mismatch %s.UnexpectedKindError\n", mmdbdata)
	fmt.Fprintf(
		out,
		"\tif !%s.As(readErr, &mismatch) || mismatch.Actual != %s.KindSlice {\n",
		g.importNames[errorsPath],
		mmdbdata,
	)
	fmt.Fprintf(out, "\t\treturn target, %s.Cursor{}, readErr\n\t}\n", mmdbdata)
	fmt.Fprintf(out, "\tvar next %s.Cursor\n\tvar err error\n", mmdbdata)
	slicePlan := *g.byteSlicePlan
	slicePlan.kind = decodeSlice
	g.emitSlice(out, &slicePlan, "cursor", "target", "next", "err", 1)
	out.WriteString("\treturn target, next, err\n}\n\n")
}

func (g *generator) emitBasic(
	out *strings.Builder,
	original types.Type,
	basic *types.Basic,
	cursor, target, next, errName string,
	indent int,
) {
	pad := strings.Repeat("\t", indent)
	typeName := g.typeString(original)
	id := g.id()
	switch basic.Kind() {
	case types.String, types.Bool:
		valueType := "string"
		readMethod := "ReadString"
		if basic.Kind() == types.Bool {
			valueType = "bool"
			readMethod = "ReadBool"
		}
		fmt.Fprintf(
			out,
			"%svar value%d %s\n%svalue%d, %s, %s = %s.%s()\n",
			pad,
			id,
			valueType,
			pad,
			id,
			next,
			errName,
			cursor,
			readMethod,
		)
		fmt.Fprintf(
			out,
			"%sif %s == nil {\n%s\t%s = %s(value%d)\n%s}\n",
			pad,
			errName,
			pad,
			target,
			typeName,
			id,
			pad,
		)
	case types.Float32, types.Float64:
		fmt.Fprintf(
			out,
			"%svar value%d float64\n%svalue%d, %s, %s = %s.ReadFloat()\n",
			pad,
			id,
			pad,
			id,
			next,
			errName,
			cursor,
		)
		fmt.Fprintf(
			out,
			"%sif %s == nil {\n%s\tconverted%d := %s(value%d)\n",
			pad,
			errName,
			pad,
			id,
			typeName,
			id,
		)
		if basic.Kind() == types.Float32 {
			fmt.Fprintf(
				out,
				"%s\tif %s.IsInf(float64(converted%d), 0) && !%s.IsInf(value%d, 0) {\n",
				pad,
				g.importNames[mathPath],
				id,
				g.importNames[mathPath],
				id,
			)
			fmt.Fprintf(
				out,
				"%s\t\t%s = %s.NewUnmarshalTypeError[%s](value%d)\n%s\t} else {\n%s\t\t%s = converted%d\n%s\t}\n",
				pad,
				errName,
				g.importNames[mmdbdataPath],
				typeName,
				id,
				pad,
				pad,
				target,
				id,
				pad,
			)
		} else {
			fmt.Fprintf(out, "%s\t%s = converted%d\n", pad, target, id)
		}
		fmt.Fprintf(out, "%s}\n", pad)
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64:
		g.emitInteger(out, original, basic, cursor, target, next, errName, indent, id)
	default:
		panic("unsupported basic type")
	}
}

func (g *generator) emitInteger(
	out *strings.Builder,
	original types.Type,
	basic *types.Basic,
	cursor, target, next, errName string,
	indent, id int,
) {
	pad := strings.Repeat("\t", indent)
	typeName := g.typeString(original)
	signed := basic.Info()&types.IsInteger != 0 && basic.Info()&types.IsUnsigned == 0
	fmt.Fprintf(out, "%svar integerValue%d uint64\n", pad, id)
	fmt.Fprintf(out, "%svar integerSigned%d bool\n", pad, id)
	fmt.Fprintf(
		out,
		"%sintegerValue%d, integerSigned%d, %s, %s = %s.ReadInteger()\n",
		pad,
		id,
		id,
		next,
		errName,
		cursor,
	)
	fmt.Fprintf(
		out,
		"%sif %s == nil && integerSigned%d {\n%s\tsignedValue%d := int64(integerValue%d)\n%s\tconverted%d := %s(signedValue%d)\n",
		pad,
		errName,
		id,
		pad,
		id,
		id,
		pad,
		id,
		typeName,
		id,
	)
	if signed {
		fmt.Fprintf(out, "%s\tif int64(converted%d) != signedValue%d {\n", pad, id, id)
	} else {
		fmt.Fprintf(
			out,
			"%s\tif signedValue%d < 0 || uint64(converted%d) != uint64(signedValue%d) {\n",
			pad,
			id,
			id,
			id,
		)
	}
	fmt.Fprintf(
		out,
		"%s\t\t%s = %s.NewUnmarshalTypeError[%s](signedValue%d)\n%s\t} else {\n%s\t\t%s = converted%d\n%s\t}\n%s} else if %s == nil {\n",
		pad,
		errName,
		g.importNames[mmdbdataPath],
		typeName,
		id,
		pad,
		pad,
		target,
		id,
		pad,
		pad,
		errName,
	)
	fmt.Fprintf(out, "%s\tunsignedValue%d := integerValue%d\n", pad, id, id)
	fmt.Fprintf(out, "%s\tconverted%d := %s(unsignedValue%d)\n", pad, id, typeName, id)
	if signed {
		fmt.Fprintf(
			out,
			"%s\tif converted%d < 0 || uint64(converted%d) != unsignedValue%d {\n",
			pad,
			id,
			id,
			id,
		)
	} else {
		fmt.Fprintf(out, "%s\tif uint64(converted%d) != unsignedValue%d {\n", pad, id, id)
	}
	fmt.Fprintf(
		out,
		"%s\t\t%s = %s.NewUnmarshalTypeError[%s](unsignedValue%d)\n%s\t} else {\n%s\t\t%s = converted%d\n%s\t}\n%s}\n",
		pad,
		errName,
		g.importNames[mmdbdataPath],
		typeName,
		id,
		pad,
		pad,
		target,
		id,
		pad,
		pad,
	)
}

func (g *generator) emitSlice(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
) {
	g.emitSliceOpen(out, plan, cursor, target, next, errName, indent, "Slice()")
}

func (g *generator) emitSliceMaxSize(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
	maximum uint64,
) {
	g.emitSliceOpen(
		out,
		plan,
		cursor,
		target,
		next,
		errName,
		indent,
		fmt.Sprintf("SliceMaxSize(%d)", maximum),
	)
}

func (g *generator) emitSliceOpen(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
	openMethod string,
) {
	pad := strings.Repeat("\t", indent)
	mmdbdata := g.importNames[mmdbdataPath]
	id := g.id()
	fmt.Fprintf(out, "%svalues%d, openErr%d := %s.%s\n", pad, id, id, cursor, openMethod)
	fmt.Fprintf(
		out,
		"%sif openErr%d != nil {\n%s\t%s = %s.NormalizeUnmarshalError[%s](openErr%d)\n%s} else {\n",
		pad,
		id,
		pad,
		errName,
		mmdbdata,
		g.typeString(plan.typ),
		id,
		pad,
	)
	fmt.Fprintf(
		out,
		"%s\tsizeValue%d, sizeReady%d := values%d.SizeForCapacity(cap(%s))\n%s\tif !sizeReady%d {\n%s\t\tsizeValue%d, %s = values%d.Size()\n%s\t}\n%s\tif %s == nil {\n%s\t\tsize%d := int(sizeValue%d)\n%s\t\toldLen%d := len(%s)\n",
		pad,
		id,
		id,
		id,
		target,
		pad,
		id,
		pad,
		id,
		errName,
		id,
		pad,
		pad,
		errName,
		pad,
		id,
		id,
		pad,
		id,
		target,
	)
	fmt.Fprintf(
		out,
		"%s\tif %s == nil || cap(%s) < size%d {\n%s\t\t%s = make(%s, size%d)\n%s\t} else {\n",
		pad,
		target,
		target,
		id,
		pad,
		target,
		g.typeString(plan.typ),
		id,
		pad,
	)
	fmt.Fprintf(
		out,
		"%s\t\t%s = %s[:size%d]\n%s\t\tclear(%s)\n",
		pad,
		target,
		target,
		id,
		pad,
		target,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif oldLen%d > size%d {\n%s\t\t\tclear(%s[size%d:oldLen%d])\n%s\t\t}\n%s\t}\n",
		pad,
		id,
		id,
		pad,
		target,
		id,
		id,
		pad,
		pad,
	)
	fmt.Fprintf(out, "%s\tvar elementNext%d %s.Cursor\n", pad, id, mmdbdata)
	fmt.Fprintf(
		out,
		"%s\tfor {\n%s\t\tindexValue%d, elementCursor%d, ok%d := values%d.Next(elementNext%d)\n%s\t\tif !ok%d {\n%s\t\t\tbreak\n%s\t\t}\n%s\t\tindex%d := int(indexValue%d)\n%s\t\tvar elementErr%d error\n",
		pad,
		pad,
		id,
		id,
		id,
		id,
		id,
		pad,
		id,
		pad,
		pad,
		pad,
		id,
		id,
		pad,
		id,
	)
	g.emitDecode(
		out,
		plan.elem,
		fmt.Sprintf("elementCursor%d", id),
		fmt.Sprintf("%s[index%d]", target, id),
		fmt.Sprintf("elementNext%d", id),
		fmt.Sprintf("elementErr%d", id),
		indent+2,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif elementErr%d != nil {\n%s\t\t\t%s = %s.Errorf(\"decoding index %%d: %%w\", index%d, %s)\n%s\t\t\tbreak\n%s\t\t}\n",
		pad,
		id,
		pad,
		errName,
		g.importNames[fmtPath],
		id,
		g.errorExpression(plan.elem, fmt.Sprintf("elementErr%d", id)),
		pad,
		pad,
	)
	fmt.Fprintf(out, "%s\t}\n", pad)
	fmt.Fprintf(
		out,
		"%s\tif %s == nil {\n%s\t\t%s, %s = values%d.End()\n%s\t}\n%s\t}\n%s}\n",
		pad,
		errName,
		pad,
		next,
		errName,
		id,
		pad,
		pad,
		pad,
	)
}

func (g *generator) emitMap(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
) {
	if plan.keyPlan != nil {
		g.emitCustomKeyMap(out, plan, cursor, target, next, errName, indent)
		return
	}

	pad := strings.Repeat("\t", indent)
	mmdbdata := g.importNames[mmdbdataPath]
	id := g.id()
	fmt.Fprintf(out, "%sentries%d, openErr%d := %s.Map()\n", pad, id, id, cursor)
	fmt.Fprintf(
		out,
		"%sif openErr%d != nil {\n%s\t%s = %s.NormalizeUnmarshalError[%s](openErr%d)\n%s} else {\n",
		pad,
		id,
		pad,
		errName,
		mmdbdata,
		g.typeString(plan.typ),
		id,
		pad,
	)
	fmt.Fprintf(
		out,
		"%s\tsize%d := entries%d.Size()\n%s\tif %s == nil {\n%s\t\t%s = make(%s, int(size%d))\n%s\t}\n",
		pad,
		id,
		id,
		pad,
		target,
		pad,
		target,
		g.typeString(plan.typ),
		id,
		pad,
	)
	fmt.Fprintf(out, "%s\tvar valueNext%d %s.Cursor\n", pad, id, mmdbdata)
	fmt.Fprintf(
		out,
		"%s\tfor {\n%s\t\trawKey%d, valueCursor%d, ok%d := entries%d.Next(valueNext%d)\n%s\t\tif !ok%d {\n%s\t\t\tbreak\n%s\t\t}\n%s\t\tkey%d := %s(string(rawKey%d))\n%s\t\tvar decoded%d %s\n%s\t\tvar valueErr%d error\n",
		pad,
		pad,
		id,
		id,
		id,
		id,
		id,
		pad,
		id,
		pad,
		pad,
		pad,
		id,
		g.typeString(plan.key),
		id,
		pad,
		id,
		g.typeString(plan.elem.typ),
		pad,
		id,
	)
	g.emitDecode(
		out,
		plan.elem,
		fmt.Sprintf("valueCursor%d", id),
		fmt.Sprintf("decoded%d", id),
		fmt.Sprintf("valueNext%d", id),
		fmt.Sprintf("valueErr%d", id),
		indent+2,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif valueErr%d != nil {\n%s\t\t\t%s = %s.Errorf(\"decoding map key %%q: %%w\", key%d, %s)\n%s\t\t\tbreak\n%s\t\t}\n",
		pad,
		id,
		pad,
		errName,
		g.importNames[fmtPath],
		id,
		g.errorExpression(plan.elem, fmt.Sprintf("valueErr%d", id)),
		pad,
		pad,
	)
	fmt.Fprintf(out, "%s\t\t%s[key%d] = decoded%d\n", pad, target, id, id)
	fmt.Fprintf(out, "%s\t}\n", pad)
	fmt.Fprintf(
		out,
		"%s\tif %s == nil {\n%s\t\t%s, %s = entries%d.End()\n%s\t}\n%s}\n",
		pad,
		errName,
		pad,
		next,
		errName,
		id,
		pad,
		pad,
	)
}

func (g *generator) emitCustomKeyMap(
	out *strings.Builder,
	plan *decodePlan,
	cursor, target, next, errName string,
	indent int,
) {
	pad := strings.Repeat("\t", indent)
	mmdbdata := g.importNames[mmdbdataPath]
	id := g.id()
	fmt.Fprintf(out, "%sentries%d, openErr%d := %s.MapReader()\n", pad, id, id, cursor)
	fmt.Fprintf(
		out,
		"%sif openErr%d != nil {\n%s\t%s = %s.NormalizeUnmarshalError[%s](openErr%d)\n%s} else {\n",
		pad,
		id,
		pad,
		errName,
		mmdbdata,
		g.typeString(plan.typ),
		id,
		pad,
	)
	fmt.Fprintf(out, "%s\tsize%d := entries%d.Len()\n", pad, id, id)
	fmt.Fprintf(out, "%s\tif %s == nil {\n", pad, target)
	fmt.Fprintf(out, "%s\t\tvar sizeReady%d bool\n", pad, id)
	fmt.Fprintf(
		out,
		"%s\t\tsize%d, sizeReady%d = entries%d.SizeForAllocation()\n",
		pad,
		id,
		id,
		id,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif !sizeReady%d {\n%s\t\t\tsize%d, %s = entries%d.Size()\n%s\t\t}\n",
		pad,
		id,
		pad,
		id,
		errName,
		id,
		pad,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif %s == nil {\n%s\t\t\t%s = make(%s, int(size%d))\n%s\t\t}\n%s\t}\n",
		pad,
		errName,
		pad,
		target,
		g.typeString(plan.typ),
		id,
		pad,
		pad,
	)
	fmt.Fprintf(out, "%s\tkeyCursor%d := entries%d.First()\n", pad, id, id)
	fmt.Fprintf(
		out,
		"%s\tfor range size%d {\n%s\t\trawKey%d, valueCursor%d, keyErr%d := keyCursor%d.ReadMapKey()\n%s\t\tif keyErr%d != nil {\n%s\t\t\t%s = keyErr%d\n%s\t\t\tbreak\n%s\t\t}\n%s\t\tvar key%d %s\n",
		pad,
		id,
		pad,
		id,
		id,
		id,
		id,
		pad,
		id,
		pad,
		errName,
		id,
		pad,
		pad,
		pad,
		id,
		g.typeString(plan.key),
	)
	g.emitDecode(
		out,
		plan.keyPlan,
		fmt.Sprintf("keyCursor%d", id),
		fmt.Sprintf("key%d", id),
		"_",
		fmt.Sprintf("keyErr%d", id),
		indent+2,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif keyErr%d != nil {\n%s\t\t\t%s = %s.Errorf(\"decoding map key %%q: %%w\", string(rawKey%d), keyErr%d)\n%s\t\t\tbreak\n%s\t\t}\n%s\t\tvar decoded%d %s\n%s\t\tvar valueErr%d error\n",
		pad,
		id,
		pad,
		errName,
		g.importNames[fmtPath],
		id,
		id,
		pad,
		pad,
		pad,
		id,
		g.typeString(plan.elem.typ),
		pad,
		id,
	)
	g.emitDecode(
		out,
		plan.elem,
		fmt.Sprintf("valueCursor%d", id),
		fmt.Sprintf("decoded%d", id),
		fmt.Sprintf("keyCursor%d", id),
		fmt.Sprintf("valueErr%d", id),
		indent+2,
	)
	fmt.Fprintf(
		out,
		"%s\t\tif valueErr%d != nil {\n%s\t\t\t%s = %s.Errorf(\"decoding map key %%q: %%w\", string(rawKey%d), %s)\n%s\t\t\tbreak\n%s\t\t}\n",
		pad,
		id,
		pad,
		errName,
		g.importNames[fmtPath],
		id,
		g.errorExpression(plan.elem, fmt.Sprintf("valueErr%d", id)),
		pad,
		pad,
	)
	fmt.Fprintf(out, "%s\t\t%s[key%d] = decoded%d\n", pad, target, id, id)
	fmt.Fprintf(out, "%s\t}\n", pad)
	fmt.Fprintf(
		out,
		"%s\tif %s == nil {\n%s\t\t%s, %s = entries%d.End(keyCursor%d)\n%s\t}\n%s}\n",
		pad,
		errName,
		pad,
		next,
		errName,
		id,
		id,
		pad,
		pad,
	)
}

func (g *generator) errorExpression(plan *decodePlan, name string) string {
	for plan.kind == decodePointer {
		plan = plan.elem
	}
	if plan.kind == decodeBasic || plan.kind == decodeBytes {
		return fmt.Sprintf(
			"%s.NormalizeUnmarshalError[%s](%s)",
			g.importNames[mmdbdataPath],
			g.typeString(plan.typ),
			name,
		)
	}
	return name
}

func (g *generator) id() int {
	g.nextID++
	return g.nextID
}

func (g *generator) typeString(t types.Type) string {
	return types.TypeString(t, func(pkg *types.Package) string {
		if pkg == g.pkg.Types {
			return ""
		}
		name, ok := g.importNames[pkg.Path()]
		if !ok {
			panic("missing generated import for " + pkg.Path())
		}
		return name
	})
}

func (g *generator) prepareImports() {
	for _, info := range g.structs {
		if len(info.fields) > 0 {
			g.usesFmt = true
		}
		for _, field := range info.fields {
			g.collectPlanImports(field.plan, false)
			g.usesMath = g.usesMath || planUsesFloat32(field.plan)
		}
	}
	g.usesErrors = g.byteSlicePlan != nil

	paths := make([]string, 0, len(g.importPackages))
	for path := range g.importPackages {
		if path != mmdbdataPath {
			paths = append(paths, path)
		}
	}
	slices.Sort(paths)

	used := make(map[string]bool, len(paths)+4)
	nextGeneratedName := 1
	available := func(name string) bool {
		return !used[name] && g.pkg.Types.Scope().Lookup(name) == nil
	}
	generatedName := func() string {
		for {
			name := "_maxminddbgenImport" + strconv.Itoa(nextGeneratedName)
			nextGeneratedName++
			if available(name) {
				return name
			}
		}
	}
	reserve := func(path, preferred string) {
		name := preferred
		if !available(name) {
			name = generatedName()
		}
		g.importNames[path] = name
		used[name] = true
	}

	if g.usesErrors {
		reserve(errorsPath, "errors")
	}
	if g.usesFmt {
		reserve(fmtPath, "fmt")
	}
	if g.usesMath {
		reserve(mathPath, "math")
	}
	reserve(mmdbdataPath, "mmdbdata")
	for _, path := range paths {
		name := generatedName()
		g.importNames[path] = name
		used[name] = true
	}
}

func planUsesFloat32(plan *decodePlan) bool {
	if plan.kind == decodeBasic && plan.basic.Kind() == types.Float32 {
		return true
	}
	switch plan.kind {
	case decodePointer, decodeSlice, decodeMap:
		return planUsesFloat32(plan.elem)
	default:
		return false
	}
}

func (g *generator) collectPlanImports(plan *decodePlan, typeRequired bool) {
	if typeRequired || plan.kind == decodeBasic || plan.kind == decodeSlice ||
		plan.kind == decodeMap {
		g.collectTypeImports(plan.typ)
	}
	switch plan.kind {
	case decodePointer, decodeSlice:
		g.collectPlanImports(plan.elem, true)
	case decodeMap:
		g.collectTypeImports(plan.key)
		g.collectPlanImports(plan.elem, true)
	default:
	}
}

func (g *generator) collectTypeImports(t types.Type) {
	types.TypeString(t, func(pkg *types.Package) string {
		if pkg != g.pkg.Types {
			g.importPackages[pkg.Path()] = pkg
		}
		return pkg.Name()
	})
}

type generatedImport struct {
	path string
	name string
}

func isThirdPartyImport(path string) bool {
	first, _, _ := strings.Cut(path, "/")
	return strings.Contains(first, ".")
}

func (g *generator) emitImports(source *strings.Builder) {
	imports := make([]generatedImport, 0, len(g.importPackages)+4)
	if g.usesErrors {
		imports = append(imports, g.importSpec(errorsPath))
	}
	if g.usesFmt {
		imports = append(imports, g.importSpec(fmtPath))
	}
	if g.usesMath {
		imports = append(imports, g.importSpec(mathPath))
	}
	for path := range g.importPackages {
		if path == mmdbdataPath {
			continue
		}
		imports = append(imports, g.importSpec(path))
	}
	imports = append(imports, g.importSpec(mmdbdataPath))
	slices.SortFunc(imports, func(a, b generatedImport) int {
		aThirdParty := isThirdPartyImport(a.path)
		bThirdParty := isThirdPartyImport(b.path)
		if aThirdParty != bThirdParty {
			if aThirdParty {
				return 1
			}
			return -1
		}
		return strings.Compare(a.path, b.path)
	})

	source.WriteString("import (\n")
	thirdParty := false
	for _, generatedImport := range imports {
		if isThirdPartyImport(generatedImport.path) && !thirdParty {
			if generatedImport.path != imports[0].path {
				source.WriteString("\n")
			}
			thirdParty = true
		}
		source.WriteString("\t")
		if generatedImport.name != "" {
			source.WriteString(generatedImport.name)
			source.WriteString(" ")
		}
		source.WriteString(strconv.Quote(generatedImport.path))
		source.WriteString("\n")
	}
	source.WriteString(")\n\n")
}

func (g *generator) importSpec(path string) generatedImport {
	name := g.importNames[path]
	defaultName := path
	if index := strings.LastIndexByte(defaultName, '/'); index >= 0 {
		defaultName = defaultName[index+1:]
	}
	if name == defaultName {
		name = ""
	}
	return generatedImport{path: path, name: name}
}

func (g *generator) positionError(pos token.Pos, formatString string, args ...any) error {
	position := g.pkg.Fset.Position(pos)
	if !position.IsValid() {
		return fmt.Errorf(formatString, args...)
	}
	return fmt.Errorf("%s: %s", position, fmt.Sprintf(formatString, args...))
}
