language: go

go:
 - 1.7
 - 1.8
 - 1.9
 - "1.10"
 - 1.11
 - tip

env:
  - GO111MODULE=on

before_install:
  - "if [[ $TRAVIS_GO_VERSION == 1.11 ]]; then go get -u golang.org/x/lint/golint; fi"

install:
  - go get -v -t ./...

script:
  - go test -race -cpu 1,4 -v
  - go test -race -v -tags appengine
  - "if [[ $TRAVIS_GO_VERSION == 1.11 ]]; then go vet ./...; fi"
  - "if [[ $TRAVIS_GO_VERSION == 1.11 ]]; then golint .; fi"

sudo: false
