// Code generated by maxminddb-gen; DO NOT EDIT.
// Requires github.com/oschwald/maxminddb-golang/v2 v2.5.0 or newer.

package fixture

import (
	"fmt"
	"math"

	"github.com/oschwald/maxminddb-golang/v2/mmdbdata"
)

func maxminddbGenDecodeNested(cursor mmdbdata.Cursor, out *Nested) (mmdbdata.Cursor, error) {
	entries, err := cursor.MapReader()
	if err != nil {
		return mmdbdata.Cursor{}, mmdbdata.NormalizeUnmarshalError[Nested](err)
	}
	next := entries.First()
	for range entries.Len() {
		key, valueCursor, keyErr := next.ReadMapKey()
		if keyErr != nil {
			return mmdbdata.Cursor{}, keyErr
		}
		switch string(key) {
		case "name":
			var value1 string
			value1, next, err = valueCursor.ReadString()
			if err == nil {
				out.Name = string(value1)
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field name: %w", mmdbdata.NormalizeUnmarshalError[string](err))
			}
		default:
			next, err = valueCursor.Skip()
		}
		if err != nil {
			return mmdbdata.Cursor{}, err
		}
	}
	return entries.End(next)
}

func maxminddbGenDecodeRecord(cursor mmdbdata.Cursor, out *Record) (mmdbdata.Cursor, error) {
	entries, err := cursor.MapReader()
	if err != nil {
		return mmdbdata.Cursor{}, mmdbdata.NormalizeUnmarshalError[Record](err)
	}
	next := entries.First()
	for range entries.Len() {
		key, valueCursor, keyErr := next.ReadMapKey()
		if keyErr != nil {
			return mmdbdata.Cursor{}, keyErr
		}
		switch string(key) {
		case "name":
			var value2 string
			value2, next, err = valueCursor.ReadString()
			if err == nil {
				out.Name = Label(value2)
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field name: %w", mmdbdata.NormalizeUnmarshalError[Label](err))
			}
		case "count":
			var integerValue3 uint64
			var integerSigned3 bool
			integerValue3, integerSigned3, next, err = valueCursor.ReadInteger()
			if err == nil && integerSigned3 {
				signedValue3 := int64(integerValue3)
				converted3 := uint8(signedValue3)
				if signedValue3 < 0 || uint64(converted3) != uint64(signedValue3) {
					err = mmdbdata.NewUnmarshalTypeError[uint8](signedValue3)
				} else {
					out.Count = converted3
				}
			} else if err == nil {
				unsignedValue3 := integerValue3
				converted3 := uint8(unsignedValue3)
				if uint64(converted3) != unsignedValue3 {
					err = mmdbdata.NewUnmarshalTypeError[uint8](unsignedValue3)
				} else {
					out.Count = converted3
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field count: %w", mmdbdata.NormalizeUnmarshalError[uint8](err))
			}
		case "temperature":
			var value4 float64
			value4, next, err = valueCursor.ReadFloat()
			if err == nil {
				converted4 := float32(value4)
				if math.IsInf(float64(converted4), 0) && !math.IsInf(value4, 0) {
					err = mmdbdata.NewUnmarshalTypeError[float32](value4)
				} else {
					out.Temperature = converted4
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field temperature: %w", mmdbdata.NormalizeUnmarshalError[float32](err))
			}
		case "enabled":
			if out.Enabled == nil {
				var decoded5 bool
				var value6 bool
				value6, next, err = valueCursor.ReadBool()
				if err == nil {
					decoded5 = bool(value6)
				}
				if err == nil {
					out.Enabled = &decoded5
				}
			} else {
				var value7 bool
				value7, next, err = valueCursor.ReadBool()
				if err == nil {
					*out.Enabled = bool(value7)
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field enabled: %w", mmdbdata.NormalizeUnmarshalError[bool](err))
			}
		case "values":
			values8, openErr8 := valueCursor.Slice()
			if openErr8 != nil {
				err = mmdbdata.NormalizeUnmarshalError[[]uint16](openErr8)
			} else {
				sizeValue8, sizeReady8 := values8.SizeForCapacity(cap(out.Values))
				if !sizeReady8 {
					sizeValue8, err = values8.Size()
				}
				if err == nil {
					size8 := int(sizeValue8)
					oldLen8 := len(out.Values)
					if out.Values == nil || cap(out.Values) < size8 {
						out.Values = make([]uint16, size8)
					} else {
						out.Values = out.Values[:size8]
						clear(out.Values)
						if oldLen8 > size8 {
							clear(out.Values[size8:oldLen8])
						}
					}
					var elementNext8 mmdbdata.Cursor
					for {
						indexValue8, elementCursor8, ok8 := values8.Next(elementNext8)
						if !ok8 {
							break
						}
						index8 := int(indexValue8)
						var elementErr8 error
						var integerValue9 uint64
						var integerSigned9 bool
						integerValue9, integerSigned9, elementNext8, elementErr8 = elementCursor8.ReadInteger()
						if elementErr8 == nil && integerSigned9 {
							signedValue9 := int64(integerValue9)
							converted9 := uint16(signedValue9)
							if signedValue9 < 0 || uint64(converted9) != uint64(signedValue9) {
								elementErr8 = mmdbdata.NewUnmarshalTypeError[uint16](signedValue9)
							} else {
								out.Values[index8] = converted9
							}
						} else if elementErr8 == nil {
							unsignedValue9 := integerValue9
							converted9 := uint16(unsignedValue9)
							if uint64(converted9) != unsignedValue9 {
								elementErr8 = mmdbdata.NewUnmarshalTypeError[uint16](unsignedValue9)
							} else {
								out.Values[index8] = converted9
							}
						}
						if elementErr8 != nil {
							err = fmt.Errorf("decoding index %d: %w", index8, mmdbdata.NormalizeUnmarshalError[uint16](elementErr8))
							break
						}
					}
					if err == nil {
						next, err = values8.End()
					}
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field values: %w", err)
			}
		case "lookup":
			entries10, openErr10 := valueCursor.Map()
			if openErr10 != nil {
				err = mmdbdata.NormalizeUnmarshalError[map[string]string](openErr10)
			} else {
				size10 := entries10.Size()
				if out.Lookup == nil {
					out.Lookup = make(map[string]string, int(size10))
				}
				var valueNext10 mmdbdata.Cursor
				for {
					rawKey10, valueCursor10, ok10 := entries10.Next(valueNext10)
					if !ok10 {
						break
					}
					key10 := string(string(rawKey10))
					var decoded10 string
					var valueErr10 error
					var value11 string
					value11, valueNext10, valueErr10 = valueCursor10.ReadString()
					if valueErr10 == nil {
						decoded10 = string(value11)
					}
					if valueErr10 != nil {
						err = fmt.Errorf("decoding map key %q: %w", key10, mmdbdata.NormalizeUnmarshalError[string](valueErr10))
						break
					}
					out.Lookup[key10] = decoded10
				}
				if err == nil {
					next, err = entries10.End()
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field lookup: %w", err)
			}
		case "nested":
			next, err = maxminddbGenDecodeNested(valueCursor, &out.Nested)
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field nested: %w", err)
			}
		case "custom":
			next, err = valueCursor.Unmarshal(&out.Custom)
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field custom: %w", err)
			}
		case "bytes":
			var bytes12 []byte
			bytes12, next, err = valueCursor.ReadBytes()
			if err == nil {
				out.Bytes = append(out.Bytes[:0], bytes12...)
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field bytes: %w", mmdbdata.NormalizeUnmarshalError[[]byte](err))
			}
		default:
			next, err = valueCursor.Skip()
		}
		if err != nil {
			return mmdbdata.Cursor{}, err
		}
	}
	return entries.End(next)
}

func (out *Nested) UnmarshalMaxMindDBCursor(cursor mmdbdata.Cursor) (mmdbdata.Cursor, error) {
	return maxminddbGenDecodeNested(cursor, out)
}

func (out *Nested) UnmarshalMaxMindDB(decoder *mmdbdata.Decoder) error {
	next, err := maxminddbGenDecodeNested(decoder.Cursor(), out)
	if err != nil {
		return err
	}
	return decoder.Advance(next)
}

func (out *Record) UnmarshalMaxMindDBCursor(cursor mmdbdata.Cursor) (mmdbdata.Cursor, error) {
	return maxminddbGenDecodeRecord(cursor, out)
}

func (out *Record) UnmarshalMaxMindDB(decoder *mmdbdata.Decoder) error {
	next, err := maxminddbGenDecodeRecord(decoder.Cursor(), out)
	if err != nil {
		return err
	}
	return decoder.Advance(next)
}
