// Code generated by maxminddb-gen; DO NOT EDIT.
// Requires github.com/oschwald/maxminddb-golang/v2 v2.6.0 or newer.

package fixture

import (
	"errors"
	"fmt"
	"math"

	"github.com/oschwald/maxminddb-golang/v2/mmdbdata"
)

func maxminddbGenDecodeByteShapes(cursor mmdbdata.Cursor, out *ByteShapes) (mmdbdata.Cursor, error) {
	entries, err := cursor.MapReader()
	if err != nil {
		return mmdbdata.Cursor{}, mmdbdata.NormalizeUnmarshalError[ByteShapes](err)
	}
	next := entries.First()
	for range entries.Len() {
		key, valueCursor, keyErr := next.ReadMapKey()
		if keyErr != nil {
			return mmdbdata.Cursor{}, keyErr
		}
		switch string(key) {
		case "pointer":
			if out.Pointer == nil {
				var decoded1 []byte
				decoded1, next, err = maxminddbGen_model_5fmaxminddb_Bytes(valueCursor, decoded1)
				if err == nil {
					out.Pointer = &decoded1
				}
			} else {
				(*out.Pointer), next, err = maxminddbGen_model_5fmaxminddb_Bytes(valueCursor, (*out.Pointer))
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field pointer: %w", mmdbdata.NormalizeUnmarshalError[[]byte](err))
			}
		case "slices":
			values2, openErr2 := valueCursor.Slice()
			if openErr2 != nil {
				err = mmdbdata.NormalizeUnmarshalError[[][]byte](openErr2)
			} else {
				sizeValue2, sizeReady2 := values2.SizeForCapacity(cap(out.Slices))
				if !sizeReady2 {
					sizeValue2, err = values2.Size()
				}
				if err == nil {
					size2 := int(sizeValue2)
					oldLen2 := len(out.Slices)
					if out.Slices == nil || cap(out.Slices) < size2 {
						out.Slices = make([][]byte, size2)
					} else {
						out.Slices = out.Slices[:size2]
						clear(out.Slices)
						if oldLen2 > size2 {
							clear(out.Slices[size2:oldLen2])
						}
					}
					var elementNext2 mmdbdata.Cursor
					for {
						indexValue2, elementCursor2, ok2 := values2.Next(elementNext2)
						if !ok2 {
							break
						}
						index2 := int(indexValue2)
						var elementErr2 error
						out.Slices[index2], elementNext2, elementErr2 = maxminddbGen_model_5fmaxminddb_Bytes(elementCursor2, out.Slices[index2])
						if elementErr2 != nil {
							err = fmt.Errorf("decoding index %d: %w", index2, mmdbdata.NormalizeUnmarshalError[[]byte](elementErr2))
							break
						}
					}
					if err == nil {
						next, err = values2.End()
					}
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field slices: %w", err)
			}
		case "lookup":
			entries3, openErr3 := valueCursor.Map()
			if openErr3 != nil {
				err = mmdbdata.NormalizeUnmarshalError[map[string][]byte](openErr3)
			} else {
				size3 := entries3.Size()
				if out.Lookup == nil {
					out.Lookup = make(map[string][]byte, int(size3))
				}
				var valueNext3 mmdbdata.Cursor
				for {
					rawKey3, valueCursor3, ok3 := entries3.Next(valueNext3)
					if !ok3 {
						break
					}
					key3 := string(string(rawKey3))
					var decoded3 []byte
					var valueErr3 error
					decoded3, valueNext3, valueErr3 = maxminddbGen_model_5fmaxminddb_Bytes(valueCursor3, decoded3)
					if valueErr3 != nil {
						err = fmt.Errorf("decoding map key %q: %w", key3, mmdbdata.NormalizeUnmarshalError[[]byte](valueErr3))
						break
					}
					out.Lookup[key3] = decoded3
				}
				if err == nil {
					next, err = entries3.End()
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field lookup: %w", err)
			}
		default:
			next, err = valueCursor.Skip()
		}
		if err != nil {
			return mmdbdata.Cursor{}, err
		}
	}
	return entries.End(next)
}

func maxminddbGenDecodeDualInterfaceRecord(cursor mmdbdata.Cursor, out *DualInterfaceRecord) (mmdbdata.Cursor, error) {
	entries, err := cursor.MapReader()
	if err != nil {
		return mmdbdata.Cursor{}, mmdbdata.NormalizeUnmarshalError[DualInterfaceRecord](err)
	}
	next := entries.First()
	for range entries.Len() {
		key, valueCursor, keyErr := next.ReadMapKey()
		if keyErr != nil {
			return mmdbdata.Cursor{}, keyErr
		}
		switch string(key) {
		case "value":
			next, err = valueCursor.UnmarshalCursor(&out.Value)
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field value: %w", err)
			}
		default:
			next, err = valueCursor.Skip()
		}
		if err != nil {
			return mmdbdata.Cursor{}, err
		}
	}
	return entries.End(next)
}

func maxminddbGenDecodeFloat64Record(cursor mmdbdata.Cursor, out *Float64Record) (mmdbdata.Cursor, error) {
	entries, err := cursor.MapReader()
	if err != nil {
		return mmdbdata.Cursor{}, mmdbdata.NormalizeUnmarshalError[Float64Record](err)
	}
	next := entries.First()
	for range entries.Len() {
		key, valueCursor, keyErr := next.ReadMapKey()
		if keyErr != nil {
			return mmdbdata.Cursor{}, keyErr
		}
		switch string(key) {
		case "value":
			var value4 float64
			value4, next, err = valueCursor.ReadFloat()
			if err == nil {
				converted4 := float64(value4)
				out.Value = converted4
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field value: %w", mmdbdata.NormalizeUnmarshalError[float64](err))
			}
		default:
			next, err = valueCursor.Skip()
		}
		if err != nil {
			return mmdbdata.Cursor{}, err
		}
	}
	return entries.End(next)
}

func maxminddbGenDecodeNested(cursor mmdbdata.Cursor, out *Nested) (mmdbdata.Cursor, error) {
	entries, err := cursor.MapReader()
	if err != nil {
		return mmdbdata.Cursor{}, mmdbdata.NormalizeUnmarshalError[Nested](err)
	}
	next := entries.First()
	for range entries.Len() {
		key, valueCursor, keyErr := next.ReadMapKey()
		if keyErr != nil {
			return mmdbdata.Cursor{}, keyErr
		}
		switch string(key) {
		case "name":
			var value5 string
			value5, next, err = valueCursor.ReadString()
			if err == nil {
				out.Name = string(value5)
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field name: %w", mmdbdata.NormalizeUnmarshalError[string](err))
			}
		default:
			next, err = valueCursor.Skip()
		}
		if err != nil {
			return mmdbdata.Cursor{}, err
		}
	}
	return entries.End(next)
}

func maxminddbGenDecodeRecord(cursor mmdbdata.Cursor, out *Record) (mmdbdata.Cursor, error) {
	entries, err := cursor.MapReader()
	if err != nil {
		return mmdbdata.Cursor{}, mmdbdata.NormalizeUnmarshalError[Record](err)
	}
	next := entries.First()
	for range entries.Len() {
		key, valueCursor, keyErr := next.ReadMapKey()
		if keyErr != nil {
			return mmdbdata.Cursor{}, keyErr
		}
		switch string(key) {
		case "name":
			var value6 string
			value6, next, err = valueCursor.ReadString()
			if err == nil {
				out.Name = Label(value6)
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field name: %w", mmdbdata.NormalizeUnmarshalError[Label](err))
			}
		case "count":
			var integerValue7 uint64
			var integerSigned7 bool
			integerValue7, integerSigned7, next, err = valueCursor.ReadInteger()
			if err == nil && integerSigned7 {
				signedValue7 := int64(integerValue7)
				converted7 := uint8(signedValue7)
				if signedValue7 < 0 || uint64(converted7) != uint64(signedValue7) {
					err = mmdbdata.NewUnmarshalTypeError[uint8](signedValue7)
				} else {
					out.Count = converted7
				}
			} else if err == nil {
				unsignedValue7 := integerValue7
				converted7 := uint8(unsignedValue7)
				if uint64(converted7) != unsignedValue7 {
					err = mmdbdata.NewUnmarshalTypeError[uint8](unsignedValue7)
				} else {
					out.Count = converted7
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field count: %w", mmdbdata.NormalizeUnmarshalError[uint8](err))
			}
		case "count32":
			var integerValue8 uint64
			var integerSigned8 bool
			integerValue8, integerSigned8, next, err = valueCursor.ReadInteger()
			if err == nil && integerSigned8 {
				signedValue8 := int64(integerValue8)
				converted8 := uint32(signedValue8)
				if signedValue8 < 0 || uint64(converted8) != uint64(signedValue8) {
					err = mmdbdata.NewUnmarshalTypeError[uint32](signedValue8)
				} else {
					out.Count32 = converted8
				}
			} else if err == nil {
				unsignedValue8 := integerValue8
				converted8 := uint32(unsignedValue8)
				if uint64(converted8) != unsignedValue8 {
					err = mmdbdata.NewUnmarshalTypeError[uint32](unsignedValue8)
				} else {
					out.Count32 = converted8
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field count32: %w", mmdbdata.NormalizeUnmarshalError[uint32](err))
			}
		case "count64":
			var integerValue9 uint64
			var integerSigned9 bool
			integerValue9, integerSigned9, next, err = valueCursor.ReadInteger()
			if err == nil && integerSigned9 {
				signedValue9 := int64(integerValue9)
				converted9 := uint64(signedValue9)
				if signedValue9 < 0 || uint64(converted9) != uint64(signedValue9) {
					err = mmdbdata.NewUnmarshalTypeError[uint64](signedValue9)
				} else {
					out.Count64 = converted9
				}
			} else if err == nil {
				unsignedValue9 := integerValue9
				converted9 := uint64(unsignedValue9)
				if uint64(converted9) != unsignedValue9 {
					err = mmdbdata.NewUnmarshalTypeError[uint64](unsignedValue9)
				} else {
					out.Count64 = converted9
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field count64: %w", mmdbdata.NormalizeUnmarshalError[uint64](err))
			}
		case "temperature":
			var value10 float64
			value10, next, err = valueCursor.ReadFloat()
			if err == nil {
				converted10 := float32(value10)
				if math.IsInf(float64(converted10), 0) && !math.IsInf(value10, 0) {
					err = mmdbdata.NewUnmarshalTypeError[float32](value10)
				} else {
					out.Temperature = converted10
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field temperature: %w", mmdbdata.NormalizeUnmarshalError[float32](err))
			}
		case "enabled":
			if out.Enabled == nil {
				var decoded11 bool
				var value12 bool
				value12, next, err = valueCursor.ReadBool()
				if err == nil {
					decoded11 = bool(value12)
				}
				if err == nil {
					out.Enabled = &decoded11
				}
			} else {
				var value13 bool
				value13, next, err = valueCursor.ReadBool()
				if err == nil {
					(*out.Enabled) = bool(value13)
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field enabled: %w", mmdbdata.NormalizeUnmarshalError[bool](err))
			}
		case "values":
			values14, openErr14 := valueCursor.Slice()
			if openErr14 != nil {
				err = mmdbdata.NormalizeUnmarshalError[[]uint16](openErr14)
			} else {
				sizeValue14, sizeReady14 := values14.SizeForCapacity(cap(out.Values))
				if !sizeReady14 {
					sizeValue14, err = values14.Size()
				}
				if err == nil {
					size14 := int(sizeValue14)
					oldLen14 := len(out.Values)
					if out.Values == nil || cap(out.Values) < size14 {
						out.Values = make([]uint16, size14)
					} else {
						out.Values = out.Values[:size14]
						clear(out.Values)
						if oldLen14 > size14 {
							clear(out.Values[size14:oldLen14])
						}
					}
					var elementNext14 mmdbdata.Cursor
					for {
						indexValue14, elementCursor14, ok14 := values14.Next(elementNext14)
						if !ok14 {
							break
						}
						index14 := int(indexValue14)
						var elementErr14 error
						var integerValue15 uint64
						var integerSigned15 bool
						integerValue15, integerSigned15, elementNext14, elementErr14 = elementCursor14.ReadInteger()
						if elementErr14 == nil && integerSigned15 {
							signedValue15 := int64(integerValue15)
							converted15 := uint16(signedValue15)
							if signedValue15 < 0 || uint64(converted15) != uint64(signedValue15) {
								elementErr14 = mmdbdata.NewUnmarshalTypeError[uint16](signedValue15)
							} else {
								out.Values[index14] = converted15
							}
						} else if elementErr14 == nil {
							unsignedValue15 := integerValue15
							converted15 := uint16(unsignedValue15)
							if uint64(converted15) != unsignedValue15 {
								elementErr14 = mmdbdata.NewUnmarshalTypeError[uint16](unsignedValue15)
							} else {
								out.Values[index14] = converted15
							}
						}
						if elementErr14 != nil {
							err = fmt.Errorf("decoding index %d: %w", index14, mmdbdata.NormalizeUnmarshalError[uint16](elementErr14))
							break
						}
					}
					if err == nil {
						next, err = values14.End()
					}
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field values: %w", err)
			}
		case "lookup":
			entries16, openErr16 := valueCursor.Map()
			if openErr16 != nil {
				err = mmdbdata.NormalizeUnmarshalError[map[string]string](openErr16)
			} else {
				size16 := entries16.Size()
				if out.Lookup == nil {
					out.Lookup = make(map[string]string, int(size16))
				}
				var valueNext16 mmdbdata.Cursor
				for {
					rawKey16, valueCursor16, ok16 := entries16.Next(valueNext16)
					if !ok16 {
						break
					}
					key16 := string(string(rawKey16))
					var decoded16 string
					var valueErr16 error
					var value17 string
					value17, valueNext16, valueErr16 = valueCursor16.ReadString()
					if valueErr16 == nil {
						decoded16 = string(value17)
					}
					if valueErr16 != nil {
						err = fmt.Errorf("decoding map key %q: %w", key16, mmdbdata.NormalizeUnmarshalError[string](valueErr16))
						break
					}
					out.Lookup[key16] = decoded16
				}
				if err == nil {
					next, err = entries16.End()
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field lookup: %w", err)
			}
		case "names":
			entries18, openErr18 := valueCursor.Map()
			if openErr18 != nil {
				err = mmdbdata.NormalizeUnmarshalError[map[Code]uint8](openErr18)
			} else {
				size18 := entries18.Size()
				if out.Names == nil {
					out.Names = make(map[Code]uint8, int(size18))
				}
				var valueNext18 mmdbdata.Cursor
				for {
					rawKey18, valueCursor18, ok18 := entries18.Next(valueNext18)
					if !ok18 {
						break
					}
					key18 := Code(string(rawKey18))
					var decoded18 uint8
					var valueErr18 error
					var integerValue19 uint64
					var integerSigned19 bool
					integerValue19, integerSigned19, valueNext18, valueErr18 = valueCursor18.ReadInteger()
					if valueErr18 == nil && integerSigned19 {
						signedValue19 := int64(integerValue19)
						converted19 := uint8(signedValue19)
						if signedValue19 < 0 || uint64(converted19) != uint64(signedValue19) {
							valueErr18 = mmdbdata.NewUnmarshalTypeError[uint8](signedValue19)
						} else {
							decoded18 = converted19
						}
					} else if valueErr18 == nil {
						unsignedValue19 := integerValue19
						converted19 := uint8(unsignedValue19)
						if uint64(converted19) != unsignedValue19 {
							valueErr18 = mmdbdata.NewUnmarshalTypeError[uint8](unsignedValue19)
						} else {
							decoded18 = converted19
						}
					}
					if valueErr18 != nil {
						err = fmt.Errorf("decoding map key %q: %w", key18, mmdbdata.NormalizeUnmarshalError[uint8](valueErr18))
						break
					}
					out.Names[key18] = decoded18
				}
				if err == nil {
					next, err = entries18.End()
				}
			}
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field names: %w", err)
			}
		case "nested":
			next, err = maxminddbGenDecodeNested(valueCursor, &out.Nested)
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field nested: %w", err)
			}
		case "custom":
			next, err = valueCursor.Unmarshal(&out.Custom)
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field custom: %w", err)
			}
		case "bytes":
			out.Bytes, next, err = maxminddbGen_model_5fmaxminddb_Bytes(valueCursor, out.Bytes)
			if err != nil {
				return mmdbdata.Cursor{}, fmt.Errorf("decoding field bytes: %w", mmdbdata.NormalizeUnmarshalError[[]byte](err))
			}
		default:
			next, err = valueCursor.Skip()
		}
		if err != nil {
			return mmdbdata.Cursor{}, err
		}
	}
	return entries.End(next)
}

func maxminddbGen_model_5fmaxminddb_Bytes(cursor mmdbdata.Cursor, target []byte) ([]byte, mmdbdata.Cursor, error) {
	decoded, next, err := cursor.ReadBytes()
	if err != nil {
		return maxminddbGen_model_5fmaxminddb_ByteSlice(cursor, target, err)
	}
	if len(decoded) == 0 && target == nil {
		return []byte{}, next, nil
	}
	return append(target[:0], decoded...), next, nil
}

func maxminddbGen_model_5fmaxminddb_ByteSlice(cursor mmdbdata.Cursor, target []byte, readErr error) ([]byte, mmdbdata.Cursor, error) {
	var mismatch mmdbdata.UnexpectedKindError
	if !errors.As(readErr, &mismatch) || mismatch.Actual != mmdbdata.KindSlice {
		return target, mmdbdata.Cursor{}, readErr
	}
	var next mmdbdata.Cursor
	var err error
	values20, openErr20 := cursor.Slice()
	if openErr20 != nil {
		err = mmdbdata.NormalizeUnmarshalError[[]byte](openErr20)
	} else {
		sizeValue20, sizeReady20 := values20.SizeForCapacity(cap(target))
		if !sizeReady20 {
			sizeValue20, err = values20.Size()
		}
		if err == nil {
			size20 := int(sizeValue20)
			oldLen20 := len(target)
			if target == nil || cap(target) < size20 {
				target = make([]byte, size20)
			} else {
				target = target[:size20]
				clear(target)
				if oldLen20 > size20 {
					clear(target[size20:oldLen20])
				}
			}
			var elementNext20 mmdbdata.Cursor
			for {
				indexValue20, elementCursor20, ok20 := values20.Next(elementNext20)
				if !ok20 {
					break
				}
				index20 := int(indexValue20)
				var elementErr20 error
				var integerValue21 uint64
				var integerSigned21 bool
				integerValue21, integerSigned21, elementNext20, elementErr20 = elementCursor20.ReadInteger()
				if elementErr20 == nil && integerSigned21 {
					signedValue21 := int64(integerValue21)
					converted21 := byte(signedValue21)
					if signedValue21 < 0 || uint64(converted21) != uint64(signedValue21) {
						elementErr20 = mmdbdata.NewUnmarshalTypeError[byte](signedValue21)
					} else {
						target[index20] = converted21
					}
				} else if elementErr20 == nil {
					unsignedValue21 := integerValue21
					converted21 := byte(unsignedValue21)
					if uint64(converted21) != unsignedValue21 {
						elementErr20 = mmdbdata.NewUnmarshalTypeError[byte](unsignedValue21)
					} else {
						target[index20] = converted21
					}
				}
				if elementErr20 != nil {
					err = fmt.Errorf("decoding index %d: %w", index20, mmdbdata.NormalizeUnmarshalError[byte](elementErr20))
					break
				}
			}
			if err == nil {
				next, err = values20.End()
			}
		}
	}
	return target, next, err
}

func (out *Nested) UnmarshalMaxMindDBCursor(cursor mmdbdata.Cursor) (mmdbdata.Cursor, error) {
	return maxminddbGenDecodeNested(cursor, out)
}

func (out *Nested) UnmarshalMaxMindDB(decoder *mmdbdata.Decoder) error {
	next, err := maxminddbGenDecodeNested(decoder.Cursor(), out)
	if err != nil {
		return err
	}
	return decoder.Advance(next)
}

func (out *Float64Record) UnmarshalMaxMindDBCursor(cursor mmdbdata.Cursor) (mmdbdata.Cursor, error) {
	return maxminddbGenDecodeFloat64Record(cursor, out)
}

func (out *Float64Record) UnmarshalMaxMindDB(decoder *mmdbdata.Decoder) error {
	next, err := maxminddbGenDecodeFloat64Record(decoder.Cursor(), out)
	if err != nil {
		return err
	}
	return decoder.Advance(next)
}

func (out *ByteShapes) UnmarshalMaxMindDBCursor(cursor mmdbdata.Cursor) (mmdbdata.Cursor, error) {
	return maxminddbGenDecodeByteShapes(cursor, out)
}

func (out *ByteShapes) UnmarshalMaxMindDB(decoder *mmdbdata.Decoder) error {
	next, err := maxminddbGenDecodeByteShapes(decoder.Cursor(), out)
	if err != nil {
		return err
	}
	return decoder.Advance(next)
}

func (out *DualInterfaceRecord) UnmarshalMaxMindDBCursor(cursor mmdbdata.Cursor) (mmdbdata.Cursor, error) {
	return maxminddbGenDecodeDualInterfaceRecord(cursor, out)
}

func (out *DualInterfaceRecord) UnmarshalMaxMindDB(decoder *mmdbdata.Decoder) error {
	next, err := maxminddbGenDecodeDualInterfaceRecord(decoder.Cursor(), out)
	if err != nil {
		return err
	}
	return decoder.Advance(next)
}

func (out *Record) UnmarshalMaxMindDBCursor(cursor mmdbdata.Cursor) (mmdbdata.Cursor, error) {
	return maxminddbGenDecodeRecord(cursor, out)
}

func (out *Record) UnmarshalMaxMindDB(decoder *mmdbdata.Decoder) error {
	next, err := maxminddbGenDecodeRecord(decoder.Cursor(), out)
	if err != nil {
		return err
	}
	return decoder.Advance(next)
}
