name: Go

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.26, 1.25]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -race -v ./...

  test-386:
    name: Test (Go 1.25, linux/386)
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.25
        uses: actions/setup-go@v7
        with:
          go-version: "1.25"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Test
        env:
          CGO_ENABLED: 0
          GOARCH: "386"
        run: go test -count=1 -v ./...
